<?php
/** Run: php tests/smoke-artifact-run-primitives.php */
if ( ! defined( 'ABSPATH' ) ) { define( 'ABSPATH', dirname( __DIR__ ) . '/' ); }
class WP_Error { public function __construct( private string $code, private string $message = '', private mixed $data = null ) {} public function get_error_code(): string{return $this->code;} }
function is_wp_error( $value ): bool { return $value instanceof WP_Error; }
function wp_mkdir_p( string $path ): bool { return is_dir( $path ) || mkdir( $path, 0777, true ); }
function wp_json_encode( $value, int $options = 0 ) { return json_encode( $value, $options ); }
function apply_filters( string $hook, $value, ...$args ) { return isset( $GLOBALS['ssi_artifact_filters'][ $hook ] ) ? $GLOBALS['ssi_artifact_filters'][ $hook ]( $value, ...$args ) : $value; }
require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-artifact-run.php';
$root = sys_get_temp_dir() . '/ssi-artifact-primitives-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $root ); file_put_contents( $root . '/unrelated.txt', 'keep' );
$workspace = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'test', array( 'on_success' => 'purge_on_success' ) );
$released = null; $GLOBALS['ssi_artifact_filters']['static_site_importer_artifact_workspace_lock'] = static function ( $value, string $operation, string $path, $token ) use ( &$released ) { if ( 'acquire' === $operation ) { return 'provider-token'; } $released = array( $path, $token ); return true; }; $provided_lock = $workspace->acquire_lock( 'provided.lock' ); $workspace->release_lock( $provided_lock ); unset( $GLOBALS['ssi_artifact_filters']['static_site_importer_artifact_workspace_lock'] ); if ( ! is_array( $provided_lock ) || 'provider-token' !== ( $provided_lock['token'] ?? '' ) || array( $workspace->directory() . '/provided.lock', 'provider-token' ) !== $released ) { throw new RuntimeException( 'workspace locks must support an opaque runtime-owned acquire and release contract' ); }
if ( ! is_wp_error( $workspace->path( '../escape' ) ) || ! is_wp_error( $workspace->publish_raw( '/escape', 'x' ) ) ) { throw new RuntimeException( 'workspace must reject path traversal and absolute paths' ); }
if ( is_wp_error( $workspace->publish_raw( 'nested/evidence.bin', 'evidence' ) ) ) { throw new RuntimeException( 'workspace must atomically publish owned bytes' ); }
$cache = new Static_Site_Importer_Artifact_Byte_Cache( $workspace, 'payload', 1, 1024 ); $cache->put( 'one', 'body', array( 'kind' => 'test' ) ); $hit = $cache->get( 'one' ); $cache->hit();
if ( 'body' !== ( $hit['bytes'] ?? '' ) ) { throw new RuntimeException( 'cache must replay checksummed bytes and metadata' ); }
$entry = glob( $workspace->directory() . '/cache/payload/*.entry' )[0] ?? ''; file_put_contents( $entry, 'corrupt' ); if ( null !== $cache->get( 'one' ) || 1 !== ( $cache->evidence()['corrupt_entries'] ?? 0 ) ) { throw new RuntimeException( 'cache corruption must recover as a miss' ); }
$cache->put( 'two', str_repeat( 'x', 2048 ), array() ); if ( 1 > ( $cache->evidence()['bypassed'] ?? 0 ) ) { throw new RuntimeException( 'cache capacity must bypass oversized entries' ); }
$cursor = Static_Site_Importer_Artifact_Batch_Cursor::create( array( 'a', 'b', 'c' ), 2 ); $cursor = Static_Site_Importer_Artifact_Batch_Cursor::complete( $cursor, 0 ); $cursor = Static_Site_Importer_Artifact_Batch_Cursor::split( $cursor, 1 ); if ( 1 !== Static_Site_Importer_Artifact_Batch_Cursor::next( $cursor ) || 'a' !== $cursor[0]['units'][0] || 3 !== count( $cursor ) ) { throw new RuntimeException( 'cursor must preserve deterministic completed work and split lineage' ); }
$path = $root . '/manifest.json'; $manifest = new Static_Site_Importer_Artifact_Run_Manifest( $path, 'identity', 'test/v1', array( 'target' => 'one' ) ); $data = array( 'schema' => 'test/v1', 'source' => array( 'identity' => 'identity' ), 'contract' => array( 'target' => 'one' ), 'state' => 'completed', 'final_result' => array( 'ok' => true ) ); $manifest->save( $data ); if ( array( 'ok' => true ) !== $manifest->load()['final_result'] || array( 'ok' => true ) !== $manifest->replay() ) { throw new RuntimeException( 'manifest must atomically save and replay completed results' ); }
$mismatch = new Static_Site_Importer_Artifact_Run_Manifest( $path, 'other', 'test/v1', array( 'target' => 'two' ) ); if ( ! is_wp_error( $mismatch->load() ) ) { throw new RuntimeException( 'manifest identity and contract mismatches must be rejected' ); }
$receipt = $workspace->purge(); if ( 'purged' !== $receipt['status'] || empty( $receipt['removed'] ) || ! is_file( $root . '/unrelated.txt' ) || is_dir( $workspace->directory() ) ) { throw new RuntimeException( 'purge must remove only owned workspace files and return a receipt' ); }
$retained = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'retained', array( 'on_success' => 'retain', 'expires_at' => gmdate( 'c', time() - 1 ) ) ); $created_at = json_decode( (string) $retained->read_raw( 'workspace.json' ), true )['created_at'] ?? ''; $reopened = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'retained' ); if ( $created_at !== ( json_decode( (string) $reopened->read_raw( 'workspace.json' ), true )['created_at'] ?? '' ) || ! $reopened->is_expired() || 'purged' !== $reopened->purge_expired()['status'] ) { throw new RuntimeException( 'workspace must retain stable ownership metadata and enforce expiry' ); }
$metadata_race = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'metadata-race', array( 'expires_at' => gmdate( 'c', time() - 1 ) ) ); unlink( $metadata_race->directory() . '/workspace.json' ); set_error_handler( static function ( int $severity, string $message ): never { throw new RuntimeException( $message ); } ); try { $expired = Static_Site_Importer_Artifact_Run_Workspace::purge_expired_in( $root ); } finally { restore_error_handler(); } if ( ! empty( $expired ) || ! is_dir( $metadata_race->directory() ) ) { throw new RuntimeException( 'expired workspace discovery must tolerate concurrent metadata removal without creating a cleanup receipt' ); } $metadata_race->purge();
$link = $root . '/linked-root'; if ( function_exists( 'symlink' ) && symlink( sys_get_temp_dir(), $link ) ) { try { new Static_Site_Importer_Artifact_Run_Workspace( $link, 'unsafe' ); throw new RuntimeException( 'symlink workspace root must be rejected' ); } catch ( RuntimeException $expected ) {} }
$nested = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'nested' ); if ( function_exists( 'symlink' ) && symlink( sys_get_temp_dir(), $nested->directory() . '/linked' ) && ! is_wp_error( $nested->publish_raw( 'linked/escape', 'no' ) ) ) { throw new RuntimeException( 'nested workspace symlinks must be rejected' ); } $nested->purge();
$partial = new Static_Site_Importer_Artifact_Run_Workspace( $root, 'partial' ); $outside = $root . '/outside.txt'; file_put_contents( $outside, 'outside' ); if ( function_exists( 'symlink' ) && symlink( $outside, $partial->directory() . '/outside-link' ) ) { $partial_receipt = $partial->purge(); if ( 'partial' !== $partial_receipt['status'] || ! is_file( $outside ) || empty( $partial_receipt['skipped'] ) ) { throw new RuntimeException( 'purge must report skipped symlinks without touching their targets' ); } unlink( $partial->directory() . '/outside-link' ); $partial->purge(); }
echo "Artifact run primitive smoke passed.\n";
