<?php
/**
 * WordPress-path batch import integration smoke.
 *
 * Run: wp eval-file tests/smoke-url-batch-import-wordpress.php
 *
 * @package StaticSiteImporter
 */

if ( ! defined( 'ABSPATH' ) ) { exit( 1 ); }
$root = dirname( __DIR__ );
require_once $root . '/static-site-importer.php';
$token = sanitize_key( wp_generate_password( 10, false, false ) );
$slug = 'ssi-batch-wp-' . $token;
$host = 'batch-' . $token . '.test';
$prefix = 'ssi-batch-' . $token;
$origin = 'https://' . $host;
$work_dir = wp_upload_dir()['basedir'] . '/ssi-batch-wp-' . wp_generate_uuid4();
$responses = array(
	$origin . '/sitemap.xml' => array( 'application/xml', '<urlset><url><loc>' . $origin . '/' . $prefix . '/</loc></url><url><loc>' . $origin . '/' . $prefix . '/about/</loc></url><url><loc>' . $origin . '/' . $prefix . '/about/team/</loc></url></urlset>' ),
	$origin . '/' . $prefix . '/' => array( 'text/html', '<html><head><link rel="stylesheet" href="/' . $prefix . '/first.css"></head><body><main>Home</main></body></html>' ),
	$origin . '/' . $prefix . '/about/' => array( 'text/html', '<html><body><main>About</main></body></html>' ),
	$origin . '/' . $prefix . '/about/team/' => array( 'text/html', '<html><head><link rel="stylesheet" href="/' . $prefix . '/second.css"></head><body><main>Team</main></body></html>' ),
	$origin . '/' . $prefix . '/first.css' => array( 'text/css', '.first{color:red}' ), $origin . '/' . $prefix . '/second.css' => array( 'text/css', '.second{color:blue}' ),
);
$fetcher = static function ( string $url, array $args ) use ( $responses ) { return isset( $responses[ $url ] ) ? array( 'body' => $responses[ $url ][1], 'metadata' => array( 'content_type' => $responses[ $url ][0], 'final_url' => $url ) ) : new WP_Error( 'fixture_missing', $url ); };
$request = array( 'url' => $origin . '/' . $prefix . '/', 'work_dir' => $work_dir, 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 2, 'request_delay_ms' => 0, 'max_assets' => 10 ) );
$input = array( 'slug' => $slug, 'name' => 'SSI Batch WP', 'activate' => true, 'overwrite' => false );
$before = get_stylesheet(); $calls = 0;
$first = Static_Site_Importer_URL_Batch_Import::import( $request, $input, $fetcher, static function ( array $artifact, array $args ) use ( &$calls ) { if ( 1 === $calls++ ) { return new WP_Error( 'injected_batch_failure', 'resume test' ); } return Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args ); } );
$run_id = is_wp_error( $first ) ? (string) ( $first->get_error_data()['run']['source']['identity'] ?? '' ) : '';
$first_about = get_page_by_path( $prefix . '/about', OBJECT, 'page' );
if ( ! is_wp_error( $first ) || '' === $run_id || $before !== get_stylesheet() || ! $first_about || $run_id !== (string) ( json_decode( (string) get_post_meta( $first_about->ID, '_static_site_importer_provenance', true ), true )['import_run_id'] ?? '' ) ) { throw new RuntimeException( 'first batch must materialize this invocation routes and provenance without activating after injected failure' ); }
$resumed = Static_Site_Importer_URL_Batch_Import::import( $request, $input, $fetcher, static fn( array $artifact, array $args ) => Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args ) );
$active_slug = sanitize_key( $slug );
$theme_dir = get_theme_root() . '/' . $active_slug;
$about = get_page_by_path( $prefix . '/about', OBJECT, 'page' ); $team = get_page_by_path( $prefix . '/about/team', OBJECT, 'page' );
$bootstrap = (string) file_get_contents( $theme_dir . '/functions.php' ) . implode( '', array_map( static fn( string $path ): string => (string) file_get_contents( $path ), glob( $theme_dir . '/static-site-importer-batch-bootstrap/*.php' ) ?: array() ) );
if ( is_wp_error( $resumed ) || get_stylesheet() !== $active_slug || ! $about || ! $team || $run_id !== (string) ( json_decode( (string) get_post_meta( $about->ID, '_static_site_importer_provenance', true ), true )['import_run_id'] ?? '' ) || $run_id !== (string) ( json_decode( (string) get_post_meta( $team->ID, '_static_site_importer_provenance', true ), true )['import_run_id'] ?? '' ) || (int) $team->post_parent !== (int) $about->ID || ! is_file( $theme_dir . '/functions.php' ) || ! str_contains( (string) file_get_contents( $theme_dir . '/assets/website/' . $prefix . '/first.css' ), '.first' ) || ! str_contains( (string) file_get_contents( $theme_dir . '/assets/website/' . $prefix . '/second.css' ), '.second' ) || ! str_contains( $bootstrap, 'assets/website/' . $prefix . '/first.css' ) || ! str_contains( $bootstrap, 'assets/website/' . $prefix . '/second.css' ) || 'completed' !== ( $resumed['url_batch_run']['status'] ?? '' ) ) { throw new RuntimeException( 'resumed batches must retain this invocation active bootstrap CSS behavior, assets, nested parents, terminal activation, and aggregate evidence' ); }

$scope_token = sanitize_key( wp_generate_password( 10, false, false ) );
$scope_slug = 'ssi-page-ready-' . $scope_token; $scope_origin = 'https://page-ready-' . $scope_token . '.test'; $scope_option = 'ssi_page_ready_external_effect_' . $scope_token; $scope_marker = 'Scoped page ' . $scope_token; $scope_effects = 0; $scope_now = 0; $scope_requests = 0; $scope_include_font = true;
$scope_binding = '<!-- wp:paragraph {"content":"' . $scope_marker . '"} --><p>' . $scope_marker . '</p><!-- /wp:paragraph -->';
$scope_provider = static fn( string $provider, string $capability ): string => 'form' === $capability ? 'instrumented' : $provider;
$scope_adapters = static function ( array $adapters ) use ( &$scope_effects, $scope_marker, $scope_option ) { $adapters['instrumented_form'] = array( 'id' => 'instrumented_form', 'capability' => 'form', 'provider' => 'instrumented', 'waiver_arg' => 'allow_missing_instrumented', 'dependencies' => array(), 'validator' => static fn( array $manifest ): array => array( 'forms' => $manifest['forms'] ?? array(), 'errors' => array() ), 'materializer' => static function ( array $manifest ) use ( &$scope_effects, $scope_option ): array { ++$scope_effects; update_option( $scope_option, $scope_effects ); return array( 'status' => 'completed', 'counts' => array( 'created' => count( $manifest['forms'] ?? array() ) ), 'forms' => $manifest['forms'] ?? array() ); }, 'binding_callback' => static fn(): string => '<!-- wp:paragraph {"content":"' . $scope_marker . ' bound"} --><p>' . $scope_marker . ' bound</p><!-- /wp:paragraph -->' ); return $adapters; };
$scope_http = static function ( $preempt, array $args, string $url ) use ( &$scope_requests ) { if ( str_starts_with( $url, 'https://fonts.googleapis.com/' ) ) { ++$scope_requests; return array( 'response' => array( 'code' => 200 ), 'body' => "@font-face{font-family:'Inter';src:url(https://fonts.gstatic.com/s/inter/v1/inter.woff2) format('woff2');}" ); } if ( 'https://fonts.gstatic.com/s/inter/v1/inter.woff2' === $url ) { ++$scope_requests; return array( 'response' => array( 'code' => 200 ), 'body' => 'inter-font' ); } return $preempt; };
add_filter( 'ssi_form_plugin', $scope_provider, 10, 2 ); add_filter( 'static_site_importer_entity_materializers', $scope_adapters ); add_filter( 'pre_http_request', $scope_http, 10, 3 );
$scope_request = array( 'url' => $scope_origin . '/', 'work_dir' => wp_upload_dir()['basedir'] . '/ssi-page-ready-' . wp_generate_uuid4(), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'max_invocation_seconds' => 1, '_static_site_importer_clock' => static function () use ( &$scope_now ): float { return (float) $scope_now; }, 'request_delay_ms' => 0 ) );
$scope_fetcher = static function ( string $url, array $args ) use ( $scope_origin, $scope_marker, &$scope_now ) { if ( $scope_origin . '/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>' . $scope_origin . '/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( $scope_origin . '/' === $url ) { $scope_now = 2; return array( 'body' => '<main><img src="/optional.png"><p>' . $scope_marker . '</p></main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => 'optional', 'metadata' => array( 'content_type' => 'image/png', 'final_url' => $url ) ); };
$scope_importer = static function ( array $artifact, array $args ) use ( $scope_slug, $scope_binding, &$scope_include_font ) { $declarations = array( array( 'kind' => 'dependency', 'capability' => 'form', 'source_path' => 'website/index.html', 'required_for' => array( 'entity_collection:forms' ) ), array( 'kind' => 'entity_collection', 'type' => 'forms', 'source_path' => 'website/index.html', 'payload' => array( 'schema' => 'generic/forms/v1', 'entities' => array( array( 'selector' => 'form.scoped', 'source_path' => 'website/index.html', 'form' => array( 'class' => 'scoped' ), 'controls' => array(), 'bindings' => array( array( 'schema' => 'generic/block-binding/v1', 'source_path' => 'website/index.html', 'search_block_markup' => $scope_binding, 'occurrence' => 1, 'role' => 'form', 'superseded_runtime_selectors' => array() ) ) ) ) ) ) ); $compiler_artifact = array( 'entrypoint' => 'website/index.html', 'files' => array( 'functions.php' => '<?php' ), 'runtime_declarations' => $declarations ); foreach ( $artifact['files'] as $file ) { $compiler_artifact['files'][ $file['path'] ] = $file['content'] ?? base64_decode( (string) ( $file['content_base64'] ?? '' ) ); } $args['compiled_artifact_result'] = ( new Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler() )->compile( $compiler_artifact )->toArray(); if ( $scope_include_font ) { $args['compiled_artifact_result']['source_reports']['materialization_plan']['theme']['font_materialization'] = array( 'schema' => 'blocks-engine/php-transformer/font-materialization-plan/v1', 'provider' => 'google_fonts', 'fonts' => array( 'Inter' ), 'stylesheets' => array( array( 'path' => 'assets/css/source-fonts.css', 'content' => "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400');" ) ) ); } $args['slug'] = $scope_slug; $args['name'] = 'Scoped page-ready'; return Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args ); };
$scope_first = Static_Site_Importer_URL_Batch_Import::import( $scope_request, array( 'activate' => true, 'seed_entities' => true ), $scope_fetcher, $scope_importer );
$scope_page = current( array_filter( get_posts( array( 'post_type' => 'page', 'post_status' => 'any', 'numberposts' => -1 ) ), static fn( WP_Post $post ): bool => str_contains( $post->post_content, $scope_marker ) ) ); $scope_theme_dir = get_theme_root() . '/' . $scope_slug; $scope_manifest = json_decode( (string) file_get_contents( $scope_first['url_batch_run']['run_manifest'] ), true );
if ( is_wp_error( $scope_first ) || 'deadline_exhausted' !== ( $scope_first['continuation_reason'] ?? '' ) || 0 !== $scope_effects || 0 !== $scope_requests || false !== get_option( $scope_option, false ) || get_stylesheet() === $scope_slug || $scope_page || is_dir( $scope_theme_dir ) || 'pending' !== ( $scope_manifest['batches'][0]['state'] ?? '' ) || empty( $scope_manifest['batches'][0]['page_ready_deferred'] ) || 0 !== ( $scope_first['url_batch_run']['page_ready_routes'] ?? -1 ) ) { throw new RuntimeException( 'runtime-binding deferral must persist zero page-ready progress without page, theme, provider, or font side effects' ); }
$scope_include_font = false; $scope_now = 0;
$scope_final = Static_Site_Importer_URL_Batch_Import::import( $scope_request, array( 'activate' => true, 'seed_entities' => true ), $scope_fetcher, $scope_importer );
$scope_page_after = current( array_filter( get_posts( array( 'post_type' => 'page', 'post_status' => 'any', 'numberposts' => -1 ) ), static fn( WP_Post $post ): bool => str_contains( $post->post_content, $scope_marker ) ) );
remove_filter( 'ssi_form_plugin', $scope_provider, 10 ); remove_filter( 'static_site_importer_entity_materializers', $scope_adapters ); remove_filter( 'pre_http_request', $scope_http, 10 );
if ( is_wp_error( $scope_final ) || 'completed' !== ( $scope_final['url_batch_run']['status'] ?? '' ) || 1 !== $scope_effects || 0 !== $scope_requests || 1 !== (int) get_option( $scope_option ) || get_stylesheet() !== $scope_slug || ! $scope_page_after || ! str_contains( $scope_page_after->post_content, $scope_marker . ' bound' ) || ! is_file( $scope_theme_dir . '/assets/website/optional.png' ) ) { throw new RuntimeException( 'complete-snapshot hydration must apply deferred bindings, provider effects, activation, and assets once' ); }
echo "WordPress URL batch import smoke passed.\n";
