<?php
/** Run: php tests/smoke-url-batch-import.php */
if ( ! defined( 'ABSPATH' ) ) { define( 'ABSPATH', dirname( __DIR__ ) . '/' ); }
class WP_Error { public function __construct( private string $code, private string $message = '', private mixed $data = null ) {} public function get_error_code(): string { return $this->code; } public function get_error_message(): string { return $this->message; } public function get_error_data(): mixed { return $this->data; } }
function is_wp_error( $value ): bool { return $value instanceof WP_Error; }
function sanitize_file_name( string $name ): string { return trim( (string) preg_replace( '/[^A-Za-z0-9._-]+/', '-', $name ), '-' ); }
function trailingslashit( string $path ): string { return rtrim( $path, '/' ) . '/'; }
function wp_mkdir_p( string $path ): bool { return is_dir( $path ) || mkdir( $path, 0777, true ); }
function wp_json_encode( $value, int $options = 0 ) { return json_encode( $value, $options ); }
require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-url-fetcher.php';
require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-url-site-collector.php';
require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-url-import-runtime.php';

$responses = array(
	'https://batch.test/sitemap.xml' => array( 'application/xml', '<sitemapindex><sitemap><loc>https://batch.test/one.xml</loc></sitemap><sitemap><loc>https://batch.test/two.xml</loc></sitemap></sitemapindex>' ),
	'https://batch.test/one.xml' => array( 'application/xml', '<urlset><url><loc>https://batch.test/</loc></url><url><loc>https://batch.test/about/</loc></url></urlset>' ),
	'https://batch.test/two.xml' => array( 'application/xml', '<urlset><url><loc>https://batch.test/about/team/</loc></url></urlset>' ),
	'https://batch.test/' => array( 'text/html', '<main><a href="/about/">About</a><link rel="stylesheet" href="/empty.css"></main>' ),
	'https://batch.test/about/' => array( 'text/html', '<main><a href="/about/team/">Team</a></main>' ),
	'https://batch.test/about/team/' => array( 'text/html', '<main>Team</main>' ),
	'https://batch.test/empty.css' => array( 'text/css', '' ),
);
$requests = array();
$transient_failures = array();
$fetcher = static function ( string $url, array $args ) use ( &$requests, &$transient_failures, $responses ) {
	$requests[] = $url;
	if ( 'https://batch.test/about/team/' === $url && empty( $transient_failures[ $url ] ) ) { $transient_failures[ $url ] = true; return new WP_Error( 'transient_timeout', 'retry me' ); }
	if ( ! isset( $responses[ $url ] ) ) { return new WP_Error( 'missing_fixture', $url ); }
	return array( 'body' => $responses[ $url ][1], 'metadata' => array( 'content_type' => $responses[ $url ][0], 'final_url' => $url ) );
};
$work_dir = sys_get_temp_dir() . '/ssi-url-batch-' . bin2hex( random_bytes( 4 ) );
$request = array( 'url' => 'https://batch.test/', 'work_dir' => $work_dir, 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 2, 'request_delay_ms' => 0, 'max_assets' => 10 ) );
$input = array( 'activate' => true );
$artifacts = array();
$attempt = 0;
$importer = static function ( array $artifact, array $args ) use ( &$artifacts, &$attempt ) {
	$artifacts[] = array( 'artifact' => $artifact, 'args' => $args );
	if ( 1 === $attempt++ ) { return new WP_Error( 'injected_batch_failure', 'stop after the first completed batch' ); }
	return array( 'theme_slug' => 'batch-site', 'quality' => array( 'pass' => true, 'status' => 'success_with_warnings', 'metrics' => array( 'fallback_count' => 1 ), 'fallbacks' => array( array( 'html' => str_repeat( 'x', 1024 ) ) ) ), 'import_report_summary' => array( 'status' => 'completed' ) );
};
$first = Static_Site_Importer_URL_Batch_Import::import( $request, $input, $fetcher, $importer );
if ( ! is_wp_error( $first ) || 'injected_batch_failure' !== $first->get_error_code() ) { throw new RuntimeException( 'injected batch failure must retain a resumable run' ); }
$manifest_path = $first->get_error_data()['run_manifest'] ?? '';
$manifest = json_decode( (string) file_get_contents( $manifest_path ), true );
if ( 'failed' !== ( $manifest['state'] ?? '' ) || 'completed' !== ( $manifest['batches'][0]['state'] ?? '' ) || 3 !== ( $manifest['total_routes'] ?? 0 ) ) { throw new RuntimeException( 'manifest must checkpoint discovery and completed batches' ); }
if ( ! preg_match( '/^batch-[a-f0-9]{16}$/', (string) ( $manifest['batches'][0]['batch_id'] ?? '' ) ) || 64 !== strlen( (string) ( $manifest['batches'][0]['result']['snapshot_sha256'] ?? '' ) ) ) { throw new RuntimeException( 'checkpointed batches must retain stable identities and source snapshot evidence' ); }
$legacy_cache = $work_dir . '/url-response-cache-' . $manifest['source']['identity']; wp_mkdir_p( $legacy_cache ); foreach ( glob( $work_dir . '/.ssi-artifact-run-url-' . $manifest['source']['identity'] . '/cache/http-response/*.entry' ) ?: array() as $entry ) { copy( $entry, $legacy_cache . '/' . basename( $entry ) ); } $legacy_workspace = new Static_Site_Importer_Artifact_Run_Workspace( $work_dir, 'url-' . $manifest['source']['identity'] ); $legacy_workspace->purge();
$resumed = Static_Site_Importer_URL_Batch_Import::import( $request, $input, $fetcher, static fn( array $artifact, array $args ) => array( 'theme_slug' => 'batch-site', 'artifact' => $artifact, 'args' => $args, 'quality' => array( 'pass' => true, 'status' => 'success', 'metrics' => array( 'fallback_count' => 0 ), 'fallbacks' => array() ), 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( is_wp_error( $resumed ) || true !== ( $resumed['terminal_batch_result']['args']['activate'] ?? false ) || isset( $resumed['pages'] ) || 2 !== ( $resumed['url_batch_run']['completed_batches'] ?? 0 ) || 3 !== ( $resumed['import_report_summary']['completed_routes'] ?? 0 ) ) { throw new RuntimeException( 'aggregate results must retain terminal output explicitly without misrepresenting it as whole-site output' ); }
$batch_quality = $resumed['url_batch_run']['batch_quality'] ?? array();
if ( 2 !== count( $batch_quality ) || 1 !== ( $batch_quality[0]['fallback_count'] ?? -1 ) || isset( $batch_quality[0]['fallbacks'] ) || true !== ( $batch_quality[0]['pass'] ?? null ) || true !== ( $batch_quality[1]['pass'] ?? null ) ) { throw new RuntimeException( 'resumed aggregates must derive bounded quality evidence for every completed batch without retaining fallback payloads' ); }
$first_files = array_column( $artifacts[0]['artifact']['files'], null, 'path' );
$second_files = array_column( $artifacts[1]['artifact']['files'], null, 'path' );
if ( ! str_contains( (string) $first_files['website/about/index.html']['content'], 'href="/about/team/"' ) || ! isset( $first_files['website/empty.css'] ) || 2 < count( array_filter( $artifacts[0]['artifact']['files'], static fn( array $file ) => str_ends_with( $file['path'], 'index.html' ) ) ) || isset( $second_files['website/index.html'] ) || ! isset( $second_files['website/about/team/index.html'] ) || empty( $artifacts[1]['args']['preserve_existing_theme_bootstrap'] ) || 2 !== count( array_keys( $requests, 'https://batch.test/about/team/', true ) ) || 1 > ( $resumed['url_batch_run']['fetch_cache']['hits'] ?? 0 ) || is_dir( $legacy_cache ) ) { throw new RuntimeException( 'later batches must exclude the unrelated root page while legacy response cache migration preserves payload reuse' ); }
$again = Static_Site_Importer_URL_Batch_Import::import( $request, $input, $fetcher, static fn() => new WP_Error( 'should_not_run' ) );
if ( is_wp_error( $again ) || 'batch-site' !== ( $again['theme_slug'] ?? '' ) ) { throw new RuntimeException( 'terminal runs must return their saved SSI result without reimporting' ); }
$mismatch = Static_Site_Importer_URL_Batch_Import::import( $request, array( 'activate' => true, 'slug' => 'other-target' ), $fetcher, static fn() => new WP_Error( 'should_not_run' ) );
if ( ! is_wp_error( $mismatch ) || 'static_site_importer_batch_contract_mismatch' !== $mismatch->get_error_code() ) { throw new RuntimeException( 'a reused work directory must reject a mismatched import target contract' ); }
$activation_mismatch = Static_Site_Importer_URL_Batch_Import::import( $request, array( 'activate' => false ), $fetcher, static fn() => new WP_Error( 'should_not_run' ) );
if ( ! is_wp_error( $activation_mismatch ) || 'static_site_importer_batch_contract_mismatch' !== $activation_mismatch->get_error_code() ) { throw new RuntimeException( 'activation must be part of the resumable import contract' ); }
if ( glob( $work_dir . '/url-site-batch-cache-*.json' ) ) { throw new RuntimeException( 'completed batches must remove their fetched artifact cache' ); }
if ( 'completed' !== ( $resumed['url_batch_run']['status'] ?? '' ) || empty( $resumed['url_batch_run']['terminal_batch_report_path'] ) && ! array_key_exists( 'terminal_batch_report_path', $resumed['url_batch_run'] ) ) { throw new RuntimeException( 'aggregate evidence must label terminal-batch report fields explicitly' ); }
$continuation_routes = array( 'https://continuation.test/', 'https://continuation.test/one/', 'https://continuation.test/two/' );
$continuation_work_dir = sys_get_temp_dir() . '/ssi-url-continuation-' . bin2hex( random_bytes( 4 ) );
$continuation_request = array( 'url' => 'https://continuation.test/', 'work_dir' => $continuation_work_dir, 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'max_effective_batches_per_invocation' => 1, 'request_delay_ms' => 0 ) );
$continuation_imports = 0;
$continuation_fetcher = static function ( string $url, array $args ) use ( $continuation_routes ) { if ( 'https://continuation.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset>' . implode( '', array_map( static fn( string $route ): string => '<url><loc>' . $route . '</loc></url>', $continuation_routes ) ) . '</urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } return array( 'body' => '<main>' . $url . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); };
$continuation_importer = static function () use ( &$continuation_imports ) { $continuation_imports++; return array( 'theme_slug' => 'continuation', 'import_report_summary' => array( 'status' => 'completed' ) ); };
$continuation_first = Static_Site_Importer_URL_Batch_Import::import( $continuation_request, array(), $continuation_fetcher, $continuation_importer );
$continuation_manifest = json_decode( (string) file_get_contents( $continuation_first['url_batch_run']['run_manifest'] ?? '' ), true );
if ( is_wp_error( $continuation_first ) || true !== ( $continuation_first['continuation'] ?? false ) || 'continuing' !== ( $continuation_first['url_batch_run']['status'] ?? '' ) || 1 !== ( $continuation_first['url_batch_run']['effective_batches_processed'] ?? 0 ) || 1 !== ( $continuation_first['url_batch_run']['completed_routes'] ?? 0 ) || empty( $continuation_first['url_batch_run']['next_work']['batch_id'] ) || 'running' !== ( $continuation_manifest['state'] ?? '' ) || 1 !== $continuation_imports ) { throw new RuntimeException( 'cooperative imports must checkpoint and return after their configured effective batch budget' ); }
$continuation_second = Static_Site_Importer_URL_Batch_Import::import( $continuation_request, array(), $continuation_fetcher, $continuation_importer );
$continuation_final = Static_Site_Importer_URL_Batch_Import::import( $continuation_request, array(), $continuation_fetcher, $continuation_importer );
if ( is_wp_error( $continuation_second ) || true !== ( $continuation_second['continuation'] ?? false ) || is_wp_error( $continuation_final ) || 'completed' !== ( $continuation_final['url_batch_run']['status'] ?? '' ) || 3 !== ( $continuation_final['url_batch_run']['completed_routes'] ?? 0 ) || 3 !== $continuation_imports ) { throw new RuntimeException( 'cooperative continuation calls must resume the checkpointed cursor through completion' ); }
$deadline_now = 0; $deadline_fetches = array(); $deadline_imports = 0;
$deadline_request = array( 'url' => 'https://deadline.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-url-deadline-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 2, 'max_invocation_seconds' => 1, '_static_site_importer_clock' => static function () use ( &$deadline_now ) { return $deadline_now; }, 'request_delay_ms' => 0 ) );
$deadline_fetcher = static function ( string $url, array $args ) use ( &$deadline_now, &$deadline_fetches ) { $deadline_fetches[ $url ] = ( $deadline_fetches[ $url ] ?? 0 ) + 1; if ( 'https://deadline.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://deadline.test/</loc></url><url><loc>https://deadline.test/p/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://deadline.test/' === $url ) { $deadline_now = 2; } return array( 'body' => '<main>' . $url . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); };
$deadline_first = Static_Site_Importer_URL_Batch_Import::import( $deadline_request, array(), $deadline_fetcher, static function () use ( &$deadline_imports ) { $deadline_imports++; return array( 'theme_slug' => 'deadline', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $deadline_first ) || 'deadline_exhausted' !== ( $deadline_first['continuation_reason'] ?? '' ) || 0 !== ( $deadline_first['url_batch_run']['completed_routes'] ?? -1 ) || 0 !== $deadline_imports || 1 !== ( $deadline_fetches['https://deadline.test/'] ?? 0 ) || ! empty( $deadline_fetches['https://deadline.test/p/'] ) ) { throw new RuntimeException( 'deadline exhaustion during collection must yield before a new network fetch and retain the pending batch' ); }
$deadline_now = 0;
$deadline_final = Static_Site_Importer_URL_Batch_Import::import( $deadline_request, array(), $deadline_fetcher, static function () use ( &$deadline_imports ) { $deadline_imports++; return array( 'theme_slug' => 'deadline', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $deadline_final ) || 'completed' !== ( $deadline_final['url_batch_run']['status'] ?? '' ) || 2 !== ( $deadline_final['url_batch_run']['completed_routes'] ?? 0 ) || 1 !== ( $deadline_fetches['https://deadline.test/'] ?? 0 ) || 1 !== $deadline_imports ) { throw new RuntimeException( 'deadline continuations must resume from cached collection responses' ); }
$pre_import_now = 0; $pre_import_fetches = 0; $pre_import_calls = 0;
$pre_import_request = array( 'url' => 'https://pre-import-deadline.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-url-pre-import-deadline-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'max_invocation_seconds' => 1, '_static_site_importer_clock' => static function () use ( &$pre_import_now ) { return $pre_import_now; }, 'request_delay_ms' => 0 ) );
$pre_import_fetcher = static function ( string $url, array $args ) use ( &$pre_import_now, &$pre_import_fetches ) { if ( 'https://pre-import-deadline.test/' === $url ) { $pre_import_fetches++; $pre_import_now = 2; return array( 'body' => '<main>ready</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => '<urlset><url><loc>https://pre-import-deadline.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); };
$pre_import_first = Static_Site_Importer_URL_Batch_Import::import( $pre_import_request, array(), $pre_import_fetcher, static function () use ( &$pre_import_calls ) { $pre_import_calls++; return array( 'theme_slug' => 'pre-import-deadline', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $pre_import_first ) || 'deadline_exhausted' !== ( $pre_import_first['continuation_reason'] ?? '' ) || 0 !== $pre_import_calls || 1 !== $pre_import_fetches ) { throw new RuntimeException( 'a completed collection must yield before artifact import when its deadline is exhausted' ); }
$pre_import_now = 0;
$pre_import_final = Static_Site_Importer_URL_Batch_Import::import( $pre_import_request, array(), $pre_import_fetcher, static function () use ( &$pre_import_calls ) { $pre_import_calls++; return array( 'theme_slug' => 'pre-import-deadline', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $pre_import_final ) || 'completed' !== ( $pre_import_final['url_batch_run']['status'] ?? '' ) || 1 !== $pre_import_calls || 1 !== $pre_import_fetches ) { throw new RuntimeException( 'pre-import deadline continuations must retain their collected runtime for the next invocation' ); }
$page_first_now = 0; $page_first_imports = array(); $page_first_fetches = array();
$page_first_request = array( 'url' => 'https://page-first.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-page-first-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'max_invocation_seconds' => 1, '_static_site_importer_clock' => static function () use ( &$page_first_now ) { return $page_first_now; }, 'request_delay_ms' => 0 ) );
$page_first_fetcher = static function ( string $url, array $args ) use ( &$page_first_now, &$page_first_fetches ) { $page_first_fetches[] = $url; if ( 'https://page-first.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://page-first.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://page-first.test/' === $url ) { $page_first_now = 2; return array( 'body' => '<main><img src="/optional.png"></main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => 'optional', 'metadata' => array( 'content_type' => 'image/png', 'final_url' => $url ) ); };
$page_first_importer = static function ( array $artifact, array $args ) use ( &$page_first_imports ) { $page_first_imports[] = array( 'artifact' => $artifact, 'args' => $args ); return array( 'theme_slug' => 'page-first', 'import_report_summary' => array( 'status' => 'completed' ) ); };
$page_first_interrupted = Static_Site_Importer_URL_Batch_Import::import( $page_first_request, array(), $page_first_fetcher, $page_first_importer );
$page_first_manifest = json_decode( (string) file_get_contents( $page_first_interrupted['url_batch_run']['run_manifest'] ?? '' ), true );
if ( is_wp_error( $page_first_interrupted ) || 'deadline_exhausted' !== ( $page_first_interrupted['continuation_reason'] ?? '' ) || 1 !== ( $page_first_interrupted['url_batch_run']['completed_routes'] ?? 0 ) || 1 !== ( $page_first_interrupted['url_batch_run']['page_ready_routes'] ?? 0 ) || 1 !== count( $page_first_imports ) || empty( $page_first_imports[0]['args']['page_ready_checkpoint'] ) || ! str_contains( (string) ($page_first_imports[0]['artifact']['files'][0]['content'] ?? ''), 'https://page-first.test/optional.png' ) || 'page_ready' !== ($page_first_manifest['batches'][0]['state'] ?? '') || 64 !== strlen( (string) ($page_first_manifest['batches'][0]['result']['snapshot_sha256'] ?? '') ) ) { throw new RuntimeException( 'page readiness must checkpoint and materialize immutable HTML before optional hydration reaches a deadline' ); }
$page_first_now = 0;
$page_first_resumed = Static_Site_Importer_URL_Batch_Import::import( $page_first_request, array(), $page_first_fetcher, $page_first_importer );
$clean_imports = array();
$clean_request = $page_first_request; $clean_request['work_dir'] .= '-clean'; unset( $clean_request['provider_args']['max_invocation_seconds'], $clean_request['provider_args']['_static_site_importer_clock'] );
$clean = Static_Site_Importer_URL_Batch_Import::import( $clean_request, array(), $page_first_fetcher, static function ( array $artifact, array $args ) use ( &$clean_imports ) { $clean_imports[] = array( 'artifact' => $artifact, 'args' => $args ); return array( 'theme_slug' => 'page-first', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $page_first_resumed ) || is_wp_error( $clean ) || 'completed' !== ( $page_first_resumed['url_batch_run']['status'] ?? '' ) || 2 !== count( $page_first_imports ) || 1 !== count( $clean_imports ) || wp_json_encode( $page_first_imports[1]['artifact'] ) !== wp_json_encode( $clean_imports[0]['artifact'] ) || ! in_array( 'https://page-first.test/optional.png', $page_first_fetches, true ) ) { throw new RuntimeException( 'resumed optional hydration must produce the same final artifact as a clean run without repeating the ready checkpoint' ); }
$scale_routes = array();
for ( $i = 0; $i < 1144; $i++ ) { $scale_routes[] = '<url><loc>https://scale.test/page-' . $i . '/</loc></url>'; }
$scale = Static_Site_Importer_URL_Site_Collector::discover_routes( 'https://scale.test/', array( 'request_delay_ms' => 0 ), static fn( string $url, array $args ) => array( 'body' => 'https://scale.test/sitemap.xml' === $url ? '<urlset>' . implode( '', $scale_routes ) . '</urlset>' : '', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ) );
if ( 1144 !== count( $scale ) || 5000 !== ( Static_Site_Importer_URL_Site_Collector::discovery_limits()['max_discovered_routes'] ?? 0 ) ) { throw new RuntimeException( 'discovery must support the acceptance sitemap scale within explicit limits' ); }
$overflow = Static_Site_Importer_URL_Site_Collector::discover_routes( 'https://overflow.test/', array(), static fn( string $url, array $args ) => array( 'body' => '<urlset>' . implode( '', array_map( static fn( int $i ): string => '<url><loc>https://overflow.test/p-' . $i . '/</loc></url>', range( 1, 5001 ) ) ) . '</urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ) );
if ( ! is_wp_error( $overflow ) || 'static_site_importer_discovery_incomplete' !== $overflow->get_error_code() || 'routes' !== ( $overflow->get_error_data()['truncated_dimension'] ?? '' ) ) { throw new RuntimeException( 'route discovery must reject queue/route overflow with structured evidence' ); }
$asset_urls = array();
for ( $i = 0; $i < 201; $i++ ) { $asset_urls[] = 'https://assets.test/a-' . $i . '.png'; }
$asset_request = array( 'url' => 'https://assets.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-url-batch-assets-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'request_delay_ms' => 0 ) );
$asset_result = Static_Site_Importer_URL_Batch_Import::import( $asset_request, array(), static function ( string $url, array $args ) use ( $asset_urls ) { if ( 'https://assets.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://assets.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://assets.test/' === $url ) { return array( 'body' => '<main>' . implode( '', array_map( static fn( string $asset ): string => '<img src="' . $asset . '">', $asset_urls ) ) . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => 'x', 'metadata' => array( 'content_type' => 'image/png', 'final_url' => $url ) ); }, static fn( array $artifact, array $args ) => array( 'theme_slug' => 'assets', 'asset_count' => count( $artifact['files'] ?? array() ) - 1, 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( is_wp_error( $asset_result ) || 2000 !== ( $asset_result['url_batch_run']['per_batch_limits']['max_assets'] ?? 0 ) || 268435456 !== ( $asset_result['url_batch_run']['per_batch_limits']['max_total_bytes'] ?? 0 ) || 201 > ( $asset_result['terminal_batch_result']['asset_count'] ?? 0 ) ) { throw new RuntimeException( 'batch defaults must support more than legacy 200 assets with bounded per-batch limits' ); }
$lower_request = $asset_request; $lower_request['work_dir'] .= '-lower'; $lower_request['provider_args']['max_assets'] = 1;
$lower_result = Static_Site_Importer_URL_Batch_Import::import( $lower_request, array(), static fn( string $url, array $args ) => 'https://assets.test/sitemap.xml' === $url ? array( 'body' => '<urlset><url><loc>https://assets.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ) : new WP_Error( 'fixture_stop', 'lower override reached collection' ), static fn() => array() );
if ( ! is_wp_error( $lower_result ) || 1 !== ( $lower_result->get_error_data()['run']['per_batch_limits']['max_assets'] ?? 0 ) ) { throw new RuntimeException( 'caller lower per-batch asset overrides must remain honored' ); }
$split_work_dir = sys_get_temp_dir() . '/ssi-url-split-' . bin2hex( random_bytes( 4 ));
$split_routes = array( 'https://split.test/', 'https://split.test/p1/', 'https://split.test/p2/', 'https://split.test/p3/', 'https://split.test/p4/' );
$split_fetch_counts = array(); $split_fetcher = static function ( string $url, array $args ) use ( $split_routes, &$split_fetch_counts ) { $split_fetch_counts[ $url ] = ( $split_fetch_counts[ $url ] ?? 0 ) + 1; if ( 'https://split.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset>' . implode( '', array_map( static fn( string $route ): string => '<url><loc>' . $route . '</loc></url>', $split_routes ) ) . '</urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( in_array( $url, $split_routes, true ) ) { return array( 'body' => '<main>' . str_repeat( 'x', 60 ) . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return new WP_Error( 'unexpected_asset', $url ); };
$split_request = array( 'url' => 'https://split.test/', 'work_dir' => $split_work_dir, 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 4, 'max_assets' => 1, 'max_total_bytes' => 160, 'request_delay_ms' => 0 ) );
$split_calls = array(); $split_attempt = 0;
$split_first = Static_Site_Importer_URL_Batch_Import::import( $split_request, array(), $split_fetcher, static function ( array $artifact, array $args ) use ( &$split_calls, &$split_attempt ) { $split_calls[] = array_column( $artifact['files'], 'path'); if ( 1 === $split_attempt++ ) { return new WP_Error( 'split_resume_failure', 'after a completed split child' ); } return array( 'theme_slug' => 'split', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( ! is_wp_error( $split_first ) || 'split_resume_failure' !== $split_first->get_error_code() ) { throw new RuntimeException( 'split test must fail after a completed child' ); }
$split_manifest_path = $split_first->get_error_data()['run_manifest']; $split_manifest = json_decode( (string) file_get_contents( $split_manifest_path ), true );
if ( empty( array_filter( $split_manifest['diagnostics'] ?? array(), static fn( array $row ): bool => 'batch_subdivided' === ( $row['code'] ?? '' ) ) ) || 'completed' !== ( $split_manifest['batches'][0]['state'] ?? '' ) ) { throw new RuntimeException( 'oversized batch must checkpoint deterministic split lineage before resume' ); }
$completed_before_resume = count( $split_calls );
$split_final = Static_Site_Importer_URL_Batch_Import::import( $split_request, array(), $split_fetcher, static function ( array $artifact, array $args ) use ( &$split_calls ) { $split_calls[] = array_column( $artifact['files'], 'path'); return array( 'theme_slug' => 'split', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
$split_cache = $split_final['url_batch_run']['fetch_cache'] ?? array(); $split_underlying = array_sum( $split_fetch_counts );
if ( is_wp_error( $split_final ) || 5 !== ( $split_final['url_batch_run']['completed_routes'] ?? 0 ) || count( $split_calls ) <= $completed_before_resume || 1 !== ( $split_fetch_counts['https://split.test/'] ?? 0 ) || $split_underlying !== ( $split_cache['misses'] ?? -1 ) || ( $split_cache['hits'] ?? 0 ) < 1 ) { throw new RuntimeException( 'split resume must complete routes once and reuse cached root/shared fetches with truthful counters' ); }
$split_continuation_request = $split_request; $split_continuation_request['work_dir'] .= '-continuation'; $split_continuation_request['provider_args']['max_effective_batches_per_invocation'] = 1;
$split_continuation_imports = 0;
$split_continuation = Static_Site_Importer_URL_Batch_Import::import( $split_continuation_request, array(), $split_fetcher, static function () use ( &$split_continuation_imports ) { $split_continuation_imports++; return array( 'theme_slug' => 'split-continuation', 'import_report_summary' => array( 'status' => 'completed' ) ); } );
$split_next_work = $split_continuation['url_batch_run']['next_work'] ?? array(); $split_first_child = $split_continuation['batch_materialization'][0] ?? array();
if ( is_wp_error( $split_continuation ) || true !== ( $split_continuation['continuation'] ?? false ) || 0 !== ( $split_continuation['url_batch_run']['effective_batches_processed'] ?? -1 ) || 0 !== ( $split_continuation['url_batch_run']['completed_routes'] ?? -1 ) || 0 !== $split_continuation_imports || empty( $split_first_child['split_from'] ) || ( $split_first_child['batch_id'] ?? '' ) !== ( $split_next_work['batch_id'] ?? '' ) ) { throw new RuntimeException( 'cooperative split batches must checkpoint and yield before the first child is collected' ); }
$split_resumed = $split_continuation;
for ( $i = 0; $i < 20 && ! empty( $split_resumed['continuation'] ); $i++ ) { $split_resumed = Static_Site_Importer_URL_Batch_Import::import( $split_continuation_request, array(), $split_fetcher, static function () use ( &$split_continuation_imports ) { $split_continuation_imports++; return array( 'theme_slug' => 'split-continuation', 'import_report_summary' => array( 'status' => 'completed' ) ); } ); }
if ( is_wp_error( $split_resumed ) || ! empty( $split_resumed['continuation'] ) || 'completed' !== ( $split_resumed['url_batch_run']['status'] ?? '' ) || 5 !== ( $split_resumed['url_batch_run']['completed_routes'] ?? 0 ) || 1 > $split_continuation_imports ) { throw new RuntimeException( 'cooperative split continuations must resume through terminal completion' ); }
$asset_count_split_routes = array( 'https://asset-count-split.test/', 'https://asset-count-split.test/one/', 'https://asset-count-split.test/two/' );
$asset_count_split = Static_Site_Importer_URL_Batch_Import::import( array( 'url' => 'https://asset-count-split.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-url-asset-count-split-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 3, 'max_assets' => 1, 'request_delay_ms' => 0 ) ), array(), static function ( string $url, array $args ) use ( $asset_count_split_routes ) { if ( 'https://asset-count-split.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset>' . implode( '', array_map( static fn( string $route ): string => '<url><loc>' . $route . '</loc></url>', $asset_count_split_routes ) ) . '</urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( in_array( $url, $asset_count_split_routes, true ) ) { return array( 'body' => '<img src="/' . basename( rtrim( $url, '/' ) ) . '.png">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => 'asset', 'metadata' => array( 'content_type' => 'image/png', 'final_url' => $url ) ); }, static fn() => array( 'theme_slug' => 'asset-count-split', 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( is_wp_error( $asset_count_split ) || 3 !== ( $asset_count_split['url_batch_run']['completed_routes'] ?? 0 ) || empty( array_filter( $asset_count_split['url_batch_run']['diagnostics'] ?? array(), static fn( array $row ): bool => 'batch_subdivided' === ( $row['code'] ?? '' ) ) ) ) { throw new RuntimeException( 'multi-route asset-count pressure must subdivide until singleton batches fit' ); }
$asset_failure_request = array( 'url' => 'https://failure-split.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-url-failure-split-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 2, 'request_delay_ms' => 0 ) );
$asset_failure_imports = 0;
$asset_failure_result = Static_Site_Importer_URL_Batch_Import::import( $asset_failure_request, array( 'activate' => true ), static function ( string $url, array $args ) { if ( 'https://failure-split.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://failure-split.test/</loc></url><url><loc>https://failure-split.test/p/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://failure-split.test/' === $url ) { return array( 'body' => '<main>' . implode( '', array_map( static fn( int $i ): string => '<img src="/failed-' . $i . '.png?variant=' . $i . '">', range( 1, 4 ) ) ) . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } if ( 'https://failure-split.test/p/' === $url ) { return array( 'body' => '<main>' . implode( '', array_map( static fn( int $i ): string => '<img src="/failed-' . $i . '.png?variant=' . $i . '">', range( 5, 8 ) ) ) . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return new WP_Error( 'optional_asset_404', 'failed' ); }, static function ( array $artifact, array $args ) use ( &$asset_failure_imports ) { $asset_failure_imports++; return array( 'theme_slug' => 'failure-split', 'activated' => ! empty( $args['activate'] ), 'import_report_summary' => array( 'status' => 'completed' ) ); } );
if ( is_wp_error( $asset_failure_result ) || 1 !== $asset_failure_imports || 1 !== ( $asset_failure_result['url_batch_run']['completed_batches'] ?? 0 ) || true !== ( $asset_failure_result['terminal_batch_result']['activated'] ?? false ) || 8 !== ( $asset_failure_result['url_batch_run']['external_asset_retained']['count'] ?? 0 ) || 8 !== count( array_filter( $asset_failure_result['url_batch_run']['external_asset_retained']['samples'] ?? array(), static fn( array $sample ): bool => 'optional_asset_404' === ( $sample['reason'] ?? '' ) ) ) || ! empty( array_filter( $asset_failure_result['url_batch_run']['diagnostics'] ?? array(), static fn( array $row ): bool => 'batch_subdivided' === ( $row['code'] ?? '' ) ) ) ) { throw new RuntimeException( 'two-route optional asset 404 variants must import once, retain exact evidence, and activate without subdivision' ); }
$rewrite_context = Static_Site_Importer_URL_Site_Collector::collect( 'https://contexts.test/', array( 'asset_failure_policy' => 'preserve_external', 'require_complete_collection' => true, 'request_delay_ms' => 0 ), static function ( string $url, array $args ) { if ( 'https://contexts.test/sitemap.xml' === $url ) { return new WP_Error( 'no_sitemap', '' ); } if ( 'https://contexts.test/' === $url ) { return array( 'body' => '<style>.x{background:url(/inline.png)}</style><link rel="stylesheet" href="/style.css"><img srcset="/one.png 1x, /two.png?x=1#f 2x" style="background:url(/style.png)">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } if ( 'https://contexts.test/style.css' === $url ) { return array( 'body' => '@import "/import.css?x=1#f";.x{background:url(/nested.png)}', 'metadata' => array( 'content_type' => 'text/css', 'final_url' => $url ) ); } return new WP_Error( 'optional_asset_timeout', 'failed' ); } );
$context_files = is_wp_error( $rewrite_context ) ? array() : array_column( $rewrite_context['artifact']['files'], null, 'path'); $context_html = $context_files['website/index.html']['content'] ?? ''; $context_css = $context_files['website/style.css']['content'] ?? '';
if ( is_wp_error( $rewrite_context ) || ! str_contains( $context_html, 'https://contexts.test/one.png' ) || ! str_contains( $context_html, 'https://contexts.test/two.png?x=1#f' ) || ! str_contains( $context_html, 'https://contexts.test/inline.png' ) || ! str_contains( $context_html, 'https://contexts.test/style.png' ) || ! str_contains( $context_css, 'https://contexts.test/import.css?x=1#f' ) || ! str_contains( $context_css, 'https://contexts.test/nested.png' ) || 6 !== ( $rewrite_context['source_metadata']['collection']['external_asset_retained']['count'] ?? 0 ) ) { throw new RuntimeException( 'external asset preservation must cover srcset, inline CSS, fetched CSS urls and imports' ); }
$nested_limit = Static_Site_Importer_URL_Site_Collector::collect( 'https://nested.test/', array( 'max_assets' => 1, 'asset_failure_policy' => 'preserve_external', 'require_complete_collection' => true, 'request_delay_ms' => 0 ), static function ( string $url, array $args ) { if ( 'https://nested.test/sitemap.xml' === $url ) { return new WP_Error( 'none', '' ); } if ( 'https://nested.test/' === $url ) { return array( 'body' => '<link rel="stylesheet" href="/style.css">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return array( 'body' => '.x{background:url(/nested.png)}', 'metadata' => array( 'content_type' => 'text/css', 'final_url' => $url ) ); } );
if ( is_wp_error( $nested_limit ) || 1 !== ( $nested_limit['source_metadata']['collection']['external_asset_retained']['count'] ?? 0 ) || 'asset_limit' !== ( $nested_limit['source_metadata']['collection']['external_asset_retained']['samples'][0]['reason'] ?? '' ) ) { throw new RuntimeException( 'nested CSS asset admission must preserve external URLs at the asset limit' ); }
$retained_failure = Static_Site_Importer_URL_Batch_Import::import( array( 'url' => 'https://persist.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-retained-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'request_delay_ms' => 0 ) ), array(), static function ( string $url, array $args ) { if ( 'https://persist.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://persist.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://persist.test/' === $url ) { return array( 'body' => '<img src="/remote.png">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return new WP_Error( 'optional_timeout', 'failed' ); }, static fn() => array( 'theme_slug' => 'retained', 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( is_wp_error( $retained_failure ) || 1 !== ( $retained_failure['url_batch_run']['external_asset_retained']['count'] ?? 0 ) || 'optional_timeout' !== ( $retained_failure['url_batch_run']['external_asset_retained']['samples'][0]['reason'] ?? '' ) ) { throw new RuntimeException( 'singleton batch asset failures must retain the external URL and complete' ); }
$preserved_asset = Static_Site_Importer_URL_Site_Collector::collect( 'https://preserve.test/', array( 'max_assets' => 10, 'require_complete_collection' => true, 'asset_failure_policy' => 'preserve_external', 'request_delay_ms' => 0 ), static function ( string $url, array $args ) { if ( 'https://preserve.test/sitemap.xml' === $url ) { return new WP_Error( 'no_sitemap', '' ); } if ( 'https://preserve.test/' === $url ) { return array( 'body' => '<main><img src="https://preserve.test/too-big.jpg"></main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return new WP_Error( 'static_site_importer_url_too_large', 'too large' ); } );
$preserved_files = is_wp_error( $preserved_asset ) ? array() : array_column( $preserved_asset['artifact']['files'], null, 'path' );
if ( is_wp_error( $preserved_asset ) || isset( $preserved_files['website/too-big.jpg'] ) || ! str_contains( (string) $preserved_files['website/index.html']['content'], 'https://preserve.test/too-big.jpg' ) || 1 !== ( $preserved_asset['source_metadata']['collection']['external_asset_retained']['count'] ?? 0 ) || 'static_site_importer_url_too_large' !== ( $preserved_asset['source_metadata']['collection']['external_asset_retained']['samples'][0]['reason'] ?? '' ) ) { throw new RuntimeException( 'single-route optional oversized assets must remain absolute with retained-asset evidence' ); }
$strict_asset = Static_Site_Importer_URL_Site_Collector::collect( 'https://strict.test/', array( 'require_complete_collection' => true, 'request_delay_ms' => 0 ), static function ( string $url, array $args ) { if ( 'https://strict.test/sitemap.xml' === $url ) { return new WP_Error( 'no_sitemap', '' ); } if ( 'https://strict.test/' === $url ) { return array( 'body' => '<img src="/missing.png">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); } return new WP_Error( 'optional_asset_failed', 'failed' ); } );
if ( ! is_wp_error( $strict_asset ) || 'static_site_importer_site_collection_incomplete' !== $strict_asset->get_error_code() ) { throw new RuntimeException( 'strict non-batch complete collection must retain optional asset failures' ); }
$html_failed = Static_Site_Importer_URL_Site_Collector::collect( 'https://html-failed.test/', array( 'asset_failure_policy' => 'preserve_external' ), static fn( string $url, array $args ) => new WP_Error( 'html_fetch_failed', 'failed' ) );
if ( ! is_wp_error( $html_failed ) || 'html_fetch_failed' !== $html_failed->get_error_code() ) { throw new RuntimeException( 'asset preservation must never downgrade HTML page failures' ); }
$ownership_dir = sys_get_temp_dir() . '/ssi-retained-ownership-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $ownership_dir ); $ownership_workspace = new Static_Site_Importer_Artifact_Run_Workspace( $ownership_dir, 'ownership' );
$ownership_workspace->publish_json( 'batches/batch-stable.json', array( 'source_metadata' => array( 'snapshot' => array( 'files' => array( array( 'mime_type' => 'text/html', 'source_url' => 'https://ownership.test/stale/' ) ) ) ) ) );
$retained_runtime_method = new ReflectionMethod( Static_Site_Importer_URL_Batch_Import::class, 'retained_runtime' );
$owned_runtime = $retained_runtime_method->invoke( null, $ownership_workspace, 'batches/batch-stable.json', 'batches/0.json', $ownership_dir . '/legacy.json', array( 'https://ownership.test/current/' ) );
if ( null !== $owned_runtime || null !== $ownership_workspace->read_raw( 'batches/batch-stable.json' ) ) { throw new RuntimeException( 'stable retained batch payloads must prove exact route ownership before reuse' ); }
$duplicate_runtime = array( 'source_metadata' => array( 'snapshot' => array( 'files' => array( array( 'mime_type' => 'text/html', 'source_url' => 'https://ownership.test/a/' ), array( 'mime_type' => 'text/html', 'source_url' => 'https://ownership.test/b/' ) ) ) ), 'artifact' => array( 'files' => array( array( 'mime_type' => 'text/html', 'metadata' => array( 'route_path' => '/same' ) ), array( 'mime_type' => 'text/html', 'metadata' => array( 'route_path' => '/same' ) ) ) ) );
$ownership_workspace->publish_json( 'batches/batch-duplicate.json', $duplicate_runtime );
$duplicate_owned = $retained_runtime_method->invoke( null, $ownership_workspace, 'batches/batch-duplicate.json', 'batches/1.json', $ownership_dir . '/legacy-duplicate.json', array( 'https://ownership.test/a/', 'https://ownership.test/b/' ) );
if ( null !== $duplicate_owned || null !== $ownership_workspace->read_raw( 'batches/batch-duplicate.json' ) ) { throw new RuntimeException( 'retained batch payloads with colliding explicit routes must be recollected after route canonicalization upgrades' ); }
$ownership_workspace->purge();
$cache_dir = sys_get_temp_dir() . '/ssi-response-cache-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $cache_dir ); $network_calls = 0; $cache_workspace = new Static_Site_Importer_Artifact_Run_Workspace( $cache_dir, 'cache' ); $cache = new Static_Site_Importer_Artifact_Byte_Cache( $cache_workspace, 'http-response' ); $cached_fetch = static function ( string $url, array $args ) use ( &$network_calls, $cache ) { $types = isset( $args['content_types'] ) ? $args['content_types'] : null; if ( is_array( $types ) ) { sort( $types ); } $key = hash( 'sha256', $url . "\n" . wp_json_encode( array( 'max_bytes' => $args['max_bytes'] ?? null, 'content_types' => $types, 'timeout' => $args['timeout'] ?? null ) ) ); $cached = $cache->get( $key ); if ( is_array( $cached ) ) { $cache->hit(); return array( 'body' => $cached['bytes'], 'metadata' => $cached['value'] ); } $cache->miss(); $network_calls++; $response = array( 'body' => 'body-' . $network_calls, 'metadata' => array( 'content_type' => 'text/plain', 'final_url' => $url ) ); $cache->put( $key, $response['body'], $response['metadata'] ); return $response; };
$cached_fetch( 'https://cache.test/a', array( 'max_bytes' => 10, 'content_types' => array() ) ); $cached_fetch( 'https://cache.test/a', array( 'max_bytes' => 10, 'content_types' => array() ) ); $cached_fetch( 'https://cache.test/a', array( 'max_bytes' => 11, 'content_types' => array() ) );
if ( 2 !== $network_calls || 1 !== ( $cache->evidence()['hits'] ?? 0 ) ) { throw new RuntimeException( 'response cache must hit compatible constraints and miss incompatible ones' ); }
$corrupt = glob( $cache_workspace->directory() . '/cache/http-response/*.entry' ) ?: array(); foreach ( $corrupt as $path ) { file_put_contents( $path, 'corrupt' ); } $cached_fetch( 'https://cache.test/a', array( 'max_bytes' => 10, 'content_types' => array() ) );
if ( 3 !== $network_calls || 1 > ( $cache->evidence()['corrupt_entries'] ?? 0 ) ) { throw new RuntimeException( 'corrupt response cache entries must recover as misses' ); }
$cache_workspace->purge(); if ( is_dir( $cache_workspace->directory() ) ) { throw new RuntimeException( 'successful response cache cleanup must remove payloads' ); }
$poison_calls = 0; $poison_dir = sys_get_temp_dir() . '/ssi-poison-cache-' . bin2hex( random_bytes( 4 ) );
$poison_request = array( 'url' => 'https://poison.test/', 'work_dir' => $poison_dir, 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'request_delay_ms' => 0 ) );
$poison_fetcher = static function ( string $url, array $args ) use ( &$poison_calls ) { if ( 'https://poison.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://poison.test/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } $poison_calls++; return array( 'body' => 1 === $poison_calls ? '<div id="app"></div>' . str_repeat( '<script></script>', 20 ) : '<main>' . str_repeat( 'server-rendered ', 100 ) . '</main>', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); };
$poisoned = Static_Site_Importer_URL_Batch_Import::import( $poison_request, array(), $poison_fetcher, static fn() => array() );
$recovered = Static_Site_Importer_URL_Batch_Import::import( $poison_request, array(), $poison_fetcher, static fn() => array( 'theme_slug' => 'recovered', 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( ! is_wp_error( $poisoned ) || 'static_site_importer_url_client_rendered_app' !== $poisoned->get_error_code() || is_wp_error( $recovered ) || 2 !== $poison_calls ) { throw new RuntimeException( 'transient client-rendered HTML must fail truthfully without poisoning a resumable response cache' ); }
$tiny_calls = 0; $tiny_dir = sys_get_temp_dir() . '/ssi-tiny-cache-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $tiny_dir ); $tiny_workspace = new Static_Site_Importer_Artifact_Run_Workspace( $tiny_dir, 'cache' ); $tiny = new Static_Site_Importer_Artifact_Byte_Cache( $tiny_workspace, 'payload', 1, 1 ); $tiny_fetch = static function () use ( &$tiny_calls, $tiny ) { $tiny_calls++; $tiny->put( 'a', 'body', array() ); }; $tiny_fetch(); $tiny_fetch();
if ( 2 !== $tiny_calls || 2 !== ( $tiny->evidence()['bypassed'] ?? 0 ) || glob( $tiny_workspace->directory() . '/cache/payload/*.entry' ) ) { throw new RuntimeException( 'cache guards must bypass writes without creating entries' ); }
$tiny_workspace->purge();
$negative_dir = sys_get_temp_dir() . '/ssi-negative-cache-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $negative_dir ); $negative_workspace = new Static_Site_Importer_Artifact_Run_Workspace( $negative_dir, 'cache' ); $negative = new Static_Site_Importer_Artifact_Byte_Cache( $negative_workspace, 'http-response' );
$negative->put_failure( 'transient', array( 'code' => 'transient_timeout', 'message' => 'retry', 'data' => array() ), 130 ); $negative_hit = $negative->get_failure( 'transient', 100 ); $negative_expired = $negative->get_failure( 'transient', 130 ); $negative->put( 'transient', 'recovered', array( 'content_type' => 'text/plain' ) ); $negative_recovered = $negative->get( 'transient' );
if ( 'transient_timeout' !== ( $negative_hit['code'] ?? '' ) || null !== $negative_expired || 'recovered' !== ( $negative_recovered['bytes'] ?? '' ) || 1 !== ( $negative->evidence()['negative_writes'] ?? 0 ) || 1 !== ( $negative->evidence()['negative_hits'] ?? 0 ) || 1 !== ( $negative->evidence()['negative_expired'] ?? 0 ) || 1 !== ( $negative->evidence()['network_requests_avoided'] ?? 0 ) ) { throw new RuntimeException( 'negative cache entries must avoid repeated requests only until expiry, then permit successful replacement' ); }
$negative_workspace->purge();
$delay_calls = 0; $shared_asset_calls = 0;
$delay_result = Static_Site_Importer_URL_Batch_Import::import( array( 'url' => 'https://delay.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-delay-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'request_delay_ms' => 1, '_static_site_importer_delay_callback' => static function () use ( &$delay_calls ) { $delay_calls++; } ) ), array(), static function ( string $url, array $args ) use ( &$shared_asset_calls ) { if ( 'https://delay.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://delay.test/</loc></url><url><loc>https://delay.test/p/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://delay.test/shared.png' === $url ) { $shared_asset_calls++; return array( 'body' => 'asset', 'metadata' => array( 'content_type' => 'image/png', 'final_url' => $url ) ); } return array( 'body' => '<img src="/shared.png">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); }, static fn() => array( 'theme_slug' => 'delay', 'import_report_summary' => array( 'status' => 'completed' ) ) );
if ( is_wp_error( $delay_result ) || 1 !== $shared_asset_calls || 3 !== $delay_calls || 1 > ( $delay_result['url_batch_run']['fetch_cache']['network_requests_avoided'] ?? 0 ) ) { throw new RuntimeException( 'cached shared assets must avoid request delay while cache misses retain it' ); }
$negative_asset_calls = 0; $negative_delays = 0;
$negative_request = array( 'url' => 'https://negative.test/', 'work_dir' => sys_get_temp_dir() . '/ssi-negative-' . bin2hex( random_bytes( 4 ) ), 'provider_args' => array( 'collect_site' => true, 'batch_pages' => 1, 'fetch_attempts' => 2, 'request_delay_ms' => 1, '_static_site_importer_delay_callback' => static function () use ( &$negative_delays ) { $negative_delays++; } ) );
$negative_fetcher = static function ( string $url, array $args ) use ( &$negative_asset_calls ) { if ( 'https://negative.test/sitemap.xml' === $url ) { return array( 'body' => '<urlset><url><loc>https://negative.test/</loc></url><url><loc>https://negative.test/p/</loc></url></urlset>', 'metadata' => array( 'content_type' => 'application/xml', 'final_url' => $url ) ); } if ( 'https://negative.test/shared.png' === $url ) { $negative_asset_calls++; return new WP_Error( 'asset_timeout', 'temporary failure' ); } return array( 'body' => '<img src="/shared.png">', 'metadata' => array( 'content_type' => 'text/html', 'final_url' => $url ) ); };
$negative_result = Static_Site_Importer_URL_Batch_Import::import( $negative_request, array(), $negative_fetcher, static fn() => array( 'theme_slug' => 'negative', 'import_report_summary' => array( 'status' => 'completed' ) ) );
$negative_resume = Static_Site_Importer_URL_Batch_Import::import( $negative_request, array(), $negative_fetcher, static fn() => array() );
if ( is_wp_error( $negative_result ) || is_wp_error( $negative_resume ) || 2 !== $negative_asset_calls || 3 !== $negative_delays || 1 > ( $negative_result['url_batch_run']['fetch_cache']['negative_writes'] ?? 0 ) || 2 !== ( $negative_result['url_batch_run']['external_asset_retained']['count'] ?? 0 ) ) { throw new RuntimeException( 'negative cache failures must retain optional singleton assets without exposing internal cache hooks' ); }
echo "URL batch import smoke passed.\n";
