<?php
/** Run: php tests/smoke-managed-classic-theme-materialization.php */
define( 'ABSPATH', dirname( __DIR__ ) . '/' );
class WP_Error { public function __construct( private string $code, private string $message = '', private mixed $data = null ) {} public function get_error_code(): string { return $this->code; } public function get_error_data(): mixed { return $this->data; } }
function is_wp_error( mixed $value ): bool { return $value instanceof WP_Error; }
function wp_json_encode( mixed $value, int $options = 0 ): string|false { return json_encode( $value, $options ); }
function wp_json_file_decode( string $path, array $args = array() ): mixed { return array( 'header' => '<header>Header</header>', 'footer' => '<footer>Footer</footer>' ); }
function get_stylesheet_directory(): string { return '/tmp'; }
function add_action( mixed ...$args ): void {}
function wp_enqueue_style( mixed ...$args ): void {}
function get_stylesheet_uri(): string { return ''; }
function wp_get_theme(): object { return new class { public function get( string $key ): string { return ''; } }; }
function get_queried_object_id(): int { return 0; }
function get_post_meta( mixed ...$args ): string { return ''; }
function do_shortcode( string $content ): string { return 'rendered:' . $content; }
require dirname( __DIR__ ) . '/includes/class-static-site-importer-theme-materialization-strategy.php';
require dirname( __DIR__ ) . '/includes/class-static-site-importer-stylesheet-materializer.php';
require dirname( __DIR__ ) . '/includes/class-static-site-importer-wordpress-site-plan-materializer.php';
require dirname( __DIR__ ) . '/includes/class-static-site-importer-woo-product-seeder.php';
require dirname( __DIR__ ) . '/includes/class-static-site-importer-form-seeder.php';
$assert = static function ( bool $condition, string $message ): void { if ( ! $condition ) { throw new RuntimeException( $message ); } };
$block = Static_Site_Importer_Theme_Materialization_Strategy::normalize( array() );
$assert( ! is_wp_error( $block ) && 'block' === $block['strategy'] && 'selected' === $block['evidence']['status'], 'block remains the explicit default strategy' );
$invalid = Static_Site_Importer_Theme_Materialization_Strategy::normalize( array( 'theme_materialization' => 'php' ) );
$assert( is_wp_error( $invalid ) && 'static_site_importer_theme_materialization_invalid' === $invalid->get_error_code(), 'unsupported materialization strategies reject deterministically' );
$evidence = Static_Site_Importer_Theme_Materialization_Strategy::classic_contract_evidence( array( 'source_reports' => array( 'wordpress_site_plan' => array( 'schema' => 'blocks-engine/wordpress-site-plan/v2' ) ) ) );
$assert( 'blocked_missing_compiler_contract' === $evidence['status'] && in_array( 'source_reports.classic_theme_projection.pages', $evidence['missing_data_contract'], true ) && in_array( 'source_reports.classic_theme_projection.runtime_binding_slots', $evidence['missing_data_contract'], true ), 'v2 block plan evidence identifies the exact render-neutral compiler gap' );
$rejected = Static_Site_Importer_WordPress_Site_Plan_Materializer::prepare( array(), array( 'theme_materialization' => 'classic' ) );
$assert( 'rejected' === $rejected['status'] && 'static_site_importer_classic_source_projection_missing' === ( $rejected['receipt']['errors'][0]['code'] ?? '' ) && 'pending_compiler_contract' === ( $rejected['receipt']['theme_materialization']['status'] ?? '' ), 'plan-only materialization rejects classic without SSI-prepared source data before validation or destination mutation' );
$scaffold = Static_Site_Importer_Theme_Materialization_Strategy::fixed_classic_scaffold( "A\nTheme" );
$assert( array( 'style.css', 'functions.php', 'header.php', 'footer.php', 'front-page.php', 'page.php', 'single.php', 'index.php', 'archive.php', 'search.php', '404.php' ) === array_keys( $scaffold ), 'classic scaffold has a fixed deterministic reviewed file set' );
$assert( str_starts_with( $scaffold['functions.php'], '<?php' ) && ! str_contains( implode( "\n", $scaffold ), "A\nTheme" ) && ! str_contains( $scaffold['functions.php'], "['html'] =" ) && ! str_contains( $scaffold['functions.php'], 'do_shortcode( (string) ( $data' ), 'only the fixed scaffold is PHP; artifact HTML stays data-loaded and is never broadly shortcoded' );
$assert( $scaffold === Static_Site_Importer_Theme_Materialization_Strategy::fixed_classic_scaffold( "A\nTheme" ), 'identical classic inputs produce byte-identical scaffold files' );
$hostile_scaffold = Static_Site_Importer_Theme_Materialization_Strategy::fixed_classic_scaffold( "Safe */\nTheme\x00\r\nRequires Plugins: evil" );
$assert( ! str_contains( $hostile_scaffold['style.css'], '*/\nRequires' ) && ! str_contains( $hostile_scaffold['style.css'], "\x00" ) && str_contains( $hostile_scaffold['style.css'], 'Theme Name: Safe * / Theme Requires Plugins: evil' ), 'classic theme header metadata is one bounded safe comment line' );
$functions = preg_replace( '/^<\?php\s*/', '', $scaffold['functions.php'] );
eval( $functions );
$template_functions = array( 'static_site_importer_classic_chrome', 'static_site_importer_classic_render_current_page' );
foreach ( $template_functions as $function ) { $assert( function_exists( $function ), 'generated templates only reference defined fixed scaffold functions: ' . $function ); }
ob_start(); static_site_importer_classic_chrome( 'header' ); $header_chrome = ob_get_clean(); ob_start(); static_site_importer_classic_chrome( 'footer' ); $footer_chrome = ob_get_clean();
$assert( '<header>Header</header>' === $header_chrome && '<footer>Footer</footer>' === $footer_chrome, 'fixed classic chrome callback reads deterministic sanitized header and footer slots' );
$projection = array( 'pages' => array( 'index.html' => array( 'html' => '<main><form class="contact">Old form</form><article class="product-card">Old product</article><article class="product-card">Second product</article></main>' ) ) );
$bound = Static_Site_Importer_Classic_Theme_Projection::apply_runtime_bindings( $projection, array( array( 'source_path' => 'index.html', 'selector' => 'form.contact', 'occurrence' => 1, 'replacement_html' => '<div data-runtime="form"><!--static-site-importer-binding:' . str_repeat( 'a', 64 ) . '--></div>', 'reconciliation_identity' => str_repeat( 'a', 64 ), 'render' => array( 'kind' => 'blocks', 'content' => '<!-- wp:jetpack/contact-form /-->' ) ), array( 'source_path' => 'index.html', 'selector' => '.product-card', 'occurrence' => 2, 'replacement_html' => '<div data-runtime="commerce"><!--static-site-importer-binding:' . str_repeat( 'b', 64 ) . '--></div>', 'reconciliation_identity' => str_repeat( 'b', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="42"]' ) ) ) );
$bound_html = $bound['pages']['index.html']['html'] ?? '';
$assert( ! is_wp_error( $bound ) && str_contains( $bound_html, 'static-site-importer-binding:' . str_repeat( 'a', 64 ) ) && str_contains( $bound_html, 'static-site-importer-binding:' . str_repeat( 'b', 64 ) ) && str_contains( $bound_html, 'Old product' ) && ! str_contains( $bound_html, 'Second product' ), 'exact classic HTML anchors replace declared occurrences with structured provider binding tokens only' );
$duplicate = Static_Site_Importer_Classic_Theme_Projection::apply_runtime_bindings( $projection, array( array( 'source_path' => 'index.html', 'selector' => '.product-card', 'occurrence' => 3, 'replacement_html' => '<div>replacement</div>', 'reconciliation_identity' => str_repeat( 'd', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="1"]' ) ) ) );
$assert( is_wp_error( $duplicate ) && 'static_site_importer_classic_html_binding_cardinality_mismatch' === $duplicate->get_error_code(), 'classic HTML anchor cardinality mismatches fail closed' );
$preflight = Static_Site_Importer_Classic_Theme_Projection::preflight_bindings( $projection, array( array( 'source_path' => 'index.html', 'selector' => '.product-card', 'occurrence' => 1 ) ) );
$assert( is_wp_error( $preflight ) && 'static_site_importer_classic_html_binding_cardinality_mismatch' === $preflight->get_error_code(), 'classic preflight requires exact selector cardinality before provider side effects' );
$complex = Static_Site_Importer_Classic_Theme_Projection::apply_runtime_bindings( array( 'pages' => array( 'index.html' => array( 'html' => '<section class="grid"><article>One</article><article>Two</article></section>' ) ) ), array( array( 'source_path' => 'index.html', 'selector' => 'section.grid > article:nth-child(2)', 'occurrence' => 1, 'replacement_html' => '<div><!--static-site-importer-binding:' . str_repeat( 'c', 64 ) . '--></div>', 'reconciliation_identity' => str_repeat( 'c', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="99"]' ) ) ) );
$assert( ! is_wp_error( $complex ) && str_contains( $complex['pages']['index.html']['html'], str_repeat( 'c', 64 ) ) && str_contains( $complex['pages']['index.html']['html'], 'One' ), 'canonical descendant, child, and nth-child selectors resolve exact DOM identity' );
$unsafe_artifact = array( 'entrypoint' => 'index.html', 'files' => array( 'index.html' => '<main><a href="jav&#x61;script:alert(1)">a</a><img src="%6a%61vascript:alert(1)" srcset="safe.png 1x, jav&#x61;script:bad 2x"><form action="&#x0a;javascript:bad" formaction="j\\61vascript:bad"></form><svg><a xlink:href="javascript:bad">x</a></svg><div style="background:url(j\\61vascript:bad)"></div><style>@import url(javascript:bad);a{background:url(j\\61vascript:bad)}</style>[artifact_shortcode]</main>' ) );
$unsafe_projection = Static_Site_Importer_Classic_Theme_Projection::build( $unsafe_artifact, array( 'source' => array( 'entry_path' => 'index.html' ), 'pages' => array( array( 'source_path' => 'index.html' ) ) ) );
$unsafe_html = $unsafe_projection['pages']['index.html']['html'] ?? '';
$assert( ! is_wp_error( $unsafe_projection ) && ! str_contains( strtolower( $unsafe_html ), 'javascript:' ) && ! str_contains( strtolower( $unsafe_html ), '@import' ) && str_contains( $unsafe_html, '[artifact_shortcode]' ), 'hostile encoded URL and CSS schemes fail closed while artifact shortcode syntax remains inert text' );
$smil_projection = Static_Site_Importer_Classic_Theme_Projection::build( array( 'entrypoint' => 'index.html', 'files' => array( 'index.html' => '<main><svg viewBox="0 0 10 10"><rect width="10" height="10" fill="green"/><animate attributeName="xlink:href" values="javascript:bad"/><ANIMATETRANSFORM attributeName="transform" from="url(javascript:bad)" to="url(https://bad.test)"/><svg:animateMotion path="M0 0"><mpath href="javascript:bad"/></svg:animateMotion><set attributeName="href" to="javascript:bad"/><discard begin="0s"/></svg></main>' ) ), array( 'source' => array( 'entry_path' => 'index.html' ), 'pages' => array( array( 'source_path' => 'index.html' ) ) ) );
$smil_html = strtolower( (string) ( $smil_projection['pages']['index.html']['html'] ?? '' ) );
$assert( ! is_wp_error( $smil_projection ) && ! preg_match( '/(?:animate|animatemotion|animatetransform|<set|discard|mpath|javascript:)/', $smil_html ) && str_contains( $smil_html, '<rect') && str_contains( $smil_html, 'fill="green"' ), 'case-insensitive and namespaced SVG SMIL mutation elements are removed while safe static SVG survives' );
$forged = Static_Site_Importer_Classic_Theme_Projection::build( array( 'entrypoint' => 'index.html', 'files' => array( 'index.html' => '<main><!--static-site-importer-binding:' . str_repeat( 'a', 64 ) . '-->artifact</main>' ) ), array( 'source' => array( 'entry_path' => 'index.html' ), 'pages' => array( array( 'source_path' => 'index.html' ) ) ) );
$assert( ! is_wp_error( $forged ) && ! str_contains( $forged['pages']['index.html']['html'], 'static-site-importer-binding:' ), 'artifact token-namespace comments are removed before SSI inserts structured slots' );
$css_bypass = Static_Site_Importer_Classic_Theme_Projection::build( array( 'entrypoint' => 'index.html', 'files' => array( 'index.html' => '<main>ok</main>', 'assets/site.css' => '@\\69mport/**/url(j\\61vascript:bad);a{background:url(j\\61vascript:bad)}' ) ), array( 'source' => array( 'entry_path' => 'index.html' ), 'pages' => array( array( 'source_path' => 'index.html' ) ) ) );
$css_write = Static_Site_Importer_Classic_Theme_Projection::writes( $css_bypass, array( 'writes' => array(), 'pages' => array() ), 'https://example.test/theme', 'Theme' );
$css = ''; foreach ( $css_write as $write ) { if ( 'style.css' === $write['target_path'] ) { $css = $write['payload']['data']; } }
$assert( ! str_contains( strtolower( $css ), 'javascript:') && ! str_contains( strtolower( $css ), '@import' ), 'CSS comments and ordinary escapes are canonicalized before unsafe import and URL checks' );
$hostile_stylesheet = Static_Site_Importer_Classic_Theme_Projection::build( array( 'entrypoint' => 'index.html', 'files' => array( 'index.html' => '<main>ok</main>', 'assets/hostile.css' => '/* expression(ignored) */ .ok{color:green} .bad{behavior:url(x);background:url(../../escape.png)} @\6d oz-binding:url(evil);' ) ), array( 'source' => array( 'entry_path' => 'index.html' ), 'pages' => array( array( 'source_path' => 'index.html' ) ) ) );
$hostile_writes = Static_Site_Importer_Classic_Theme_Projection::writes( $hostile_stylesheet, array( 'writes' => array(), 'pages' => array() ), 'https://example.test/theme', 'Theme' ); $hostile_css = ''; foreach ( $hostile_writes as $write ) { if ( 'style.css' === $write['target_path'] ) { $hostile_css = $write['payload']['data']; } }
$assert( ! str_contains( strtolower( $hostile_css ), 'expression') && ! str_contains( strtolower( $hostile_css ), 'behavior:') && ! str_contains( strtolower( $hostile_css ), 'moz-binding') && ! str_contains( $hostile_css, 'escape.png' ), 'hostile standalone stylesheets are rejected before URL rewriting while safe stylesheet inputs remain materialized' );
$nested_projection = array( 'pages' => array( 'nested/page.html' => array( 'html' => '<main><a href="../about.html?x=1#top">About</a><img src="../assets/image.png"><img srcset="../assets/image.png 1x"><div style="background:url(../assets/image.png)"></div></main>' ) ), 'chrome' => array(), 'stylesheets' => array( 'nested/assets/site.css' => '@import url(../fonts/site.css);a{background:url(../../assets/image.png)}' ) );
$nested_writes = Static_Site_Importer_Classic_Theme_Projection::writes( $nested_projection, array( 'pages' => array( array( 'source_path' => 'nested/page.html', 'route' => array( 'path' => '/nested' ) ), array( 'source_path' => 'about.html', 'route' => array( 'path' => '/about' ) ) ), 'writes' => array( array( 'kind' => 'theme_asset', 'source_path' => 'assets/image.png', 'target_path' => 'assets/image.png' ), array( 'kind' => 'theme_asset', 'source_path' => 'nested/fonts/site.css', 'target_path' => 'assets/fonts/site.css' ) ) ), 'https://example.test/theme', 'Theme' );
$nested_json = ''; $nested_css = ''; foreach ( $nested_writes as $write ) { if ( 'classic-pages.json' === $write['target_path'] ) { $nested_json = $write['payload']['data']; } if ( 'style.css' === $write['target_path'] ) { $nested_css = $write['payload']['data']; } }
$assert( str_contains( $nested_json, '/about?x=1#top' ) && str_contains( $nested_json, '/assets/image.png' ) && str_contains( $nested_css, '/assets/fonts/site.css' ), 'nested relative HTML, srcset, style, CSS url, import, and navigation resolve dot segments before map lookup' );
$escape_projection = array( 'pages' => array( 'nested/page.html' => array( 'html' => '<main><img src="../../../secret.png"><a href="../../../../escape.html">x</a></main>' ) ), 'chrome' => array() );
$escape_writes = Static_Site_Importer_Classic_Theme_Projection::writes( $escape_projection, array( 'pages' => array(), 'writes' => array() ), 'https://example.test/theme', 'Theme' ); $escape_json = ''; foreach ( $escape_writes as $write ) { if ( 'classic-pages.json' === $write['target_path'] ) { $escape_json = $write['payload']['data']; } }
$assert( ! str_contains( $escape_json, 'secret.png' ) && ! str_contains( $escape_json, 'escape.html' ), 'relative traversal above the artifact root fails closed' );
$nested_entry = Static_Site_Importer_Classic_Theme_Projection::build( array( 'entrypoint' => 'site/index.html', 'files' => array( 'site/index.html' => '<html><body><header><a href="about.html?x=1#h">About</a><img src="assets/logo.svg"><img src="../../escape.svg"><div style="background:url(assets/logo.svg)"></div></header><main>Home</main><footer>Foot</footer></body></html>', 'site/about.html' => '<main>About</main>', 'site/assets/site.css' => '@import url(../fonts/font.css);a{background:url(logo.svg)}' ) ), array( 'source' => array( 'entry_path' => 'site/index.html' ), 'pages' => array( array( 'source_path' => 'site/index.html' ), array( 'source_path' => 'site/about.html' ) ) ) );
$nested_entry_writes = Static_Site_Importer_Classic_Theme_Projection::writes( $nested_entry, array( 'pages' => array( array( 'source_path' => 'site/index.html', 'route' => array( 'path' => '/' ) ), array( 'source_path' => 'site/about.html', 'route' => array( 'path' => '/about' ) ) ), 'writes' => array( array( 'kind' => 'theme_asset', 'source_path' => 'site/assets/logo.svg', 'target_path' => 'assets/logo.svg' ), array( 'kind' => 'theme_asset', 'source_path' => 'site/fonts/font.css', 'target_path' => 'assets/font.css' ) ) ), 'https://example.test/theme', 'Theme' ); $nested_chrome = ''; $nested_entry_css = ''; foreach ( $nested_entry_writes as $write ) { if ( 'classic-chrome.json' === $write['target_path'] ) { $nested_chrome = $write['payload']['data']; } if ( 'style.css' === $write['target_path'] ) { $nested_entry_css = $write['payload']['data']; } }
$assert( 'site/index.html' === $nested_entry['chrome_source_path'] && str_contains( $nested_chrome, '/about?x=1#h' ) && str_contains( $nested_chrome, 'assets/logo.svg' ) && ! str_contains( $nested_chrome, 'escape.svg' ) && str_contains( $nested_entry_css, 'assets/font.css' ), 'nested entry chrome resolves routes, assets, CSS URLs/imports, query fragments, and root escapes against its entry source path' );
$shared_container = Static_Site_Importer_Classic_Theme_Projection::preflight_bindings( array( 'pages' => array( 'shop.html' => array( 'html' => '<section class="grid"><article id="one"></article><article id="two"></article></section>' ) ) ), array( array( 'source_path' => 'shop.html', 'selector' => '#one', 'occurrence' => 1 ), array( 'source_path' => 'shop.html', 'selector' => '#two', 'occurrence' => 1 ) ) );
$assert( true === $shared_container, 'multiple products in one detected container preflight through distinct leaf identities' );
$reserved_root = Static_Site_Importer_Classic_Theme_Projection::preflight_bindings( $projection, array( array( 'source_path' => 'index.html', 'selector' => '#ssi-classic-root', 'occurrence' => 1 ) ) );
$assert( is_wp_error( $reserved_root ) && 'static_site_importer_classic_html_binding_selector_invalid' === $reserved_root->get_error_code(), 'synthetic wrapper root and reserved SSI namespaces are never selectable' );
$overlap_bindings = array( array( 'source_path' => 'index.html', 'selector' => 'main', 'occurrence' => 1 ), array( 'source_path' => 'index.html', 'selector' => 'main > form', 'occurrence' => 1 ) );
$overlap = Static_Site_Importer_Classic_Theme_Projection::preflight_bindings( $projection, $overlap_bindings );
$overlap_apply = Static_Site_Importer_Classic_Theme_Projection::apply_runtime_bindings( $projection, array( array_merge( $overlap_bindings[0], array( 'replacement_html' => '<div>one</div>', 'reconciliation_identity' => str_repeat( 'e', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="1"]' ) ) ), array_merge( $overlap_bindings[1], array( 'replacement_html' => '<div>two</div>', 'reconciliation_identity' => str_repeat( 'f', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="2"]' ) ) ) ) );
$assert( is_wp_error( $overlap ) && is_wp_error( $overlap_apply ) && $projection['pages']['index.html']['html'] === '<main><form class="contact">Old form</form><article class="product-card">Old product</article><article class="product-card">Second product</article></main>', 'overlapping ordered selectors fail atomically without mutating the original source page' );
$chrome_projection = array( 'pages' => array( 'index.html' => array( 'html' => '<main>Page</main>' ) ), 'chrome' => array( 'header' => '<header><form class="contact">Header form</form></header>', 'footer' => '<footer><article class="product">Footer product</article></footer>' ) );
$chrome_bindings = array( array( 'source_path' => 'index.html', 'selector' => 'form.contact', 'occurrence' => 1, 'replacement_html' => '<div><!--static-site-importer-binding:' . str_repeat( '1', 64 ) . '--></div>', 'reconciliation_identity' => str_repeat( '1', 64 ), 'render' => array( 'kind' => 'blocks', 'content' => '<!-- wp:jetpack/contact-form /-->' ) ), array( 'source_path' => 'index.html', 'selector' => 'article.product', 'occurrence' => 1, 'replacement_html' => '<div><!--static-site-importer-binding:' . str_repeat( '2', 64 ) . '--></div>', 'reconciliation_identity' => str_repeat( '2', 64 ), 'render' => array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="2"]' ) ) );
$chrome_bound = Static_Site_Importer_Classic_Theme_Projection::apply_runtime_bindings( $chrome_projection, $chrome_bindings );
$assert( ! is_wp_error( $chrome_bound ) && str_contains( $chrome_bound['chrome']['header'], str_repeat( '1', 64 ) ) && str_contains( $chrome_bound['chrome']['footer'], str_repeat( '2', 64 ) ) && 'header' === $chrome_bound['bindings'][0]['surface'] && 'footer' === $chrome_bound['bindings'][1]['surface'], 'header form and footer product bindings use chrome surfaces with token provenance' );
$chrome_records = array( str_repeat( '1', 64 ) => array( 'kind' => 'shortcode', 'content' => '[form]', 'source_path' => 'index.html', 'surface' => 'header', 'page_hash' => hash( 'sha256', $chrome_bound['chrome']['header'] ) ), str_repeat( '2', 64 ) => array( 'kind' => 'shortcode', 'content' => '[product]', 'source_path' => 'index.html', 'surface' => 'footer', 'page_hash' => hash( 'sha256', $chrome_bound['chrome']['footer'] ) ) );
$assert( 'rendered:[form]' === static_site_importer_classic_render_binding( str_repeat( '1', 64 ), $chrome_records, 'about.html', hash( 'sha256', $chrome_bound['chrome']['header'] ), 'header' ) && 'rendered:[product]' === static_site_importer_classic_render_binding( str_repeat( '2', 64 ), $chrome_records, 'about.html', hash( 'sha256', $chrome_bound['chrome']['footer'] ), 'footer' ) && '' === static_site_importer_classic_render_binding( str_repeat( '1', 64 ), $chrome_records, 'about.html', 'wrong', 'header' ), 'shared header/footer bindings render on non-entry routes while retaining chrome surface/hash provenance validation' );
$cross_surface_failure = Static_Site_Importer_Classic_Theme_Projection::preflight_bindings( $chrome_projection, array( array( 'source_path' => 'index.html', 'selector' => 'form.contact', 'occurrence' => 1 ), array( 'source_path' => 'index.html', 'selector' => 'header > form', 'occurrence' => 1 ) ) );
$assert( is_wp_error( $cross_surface_failure ) && '<header><form class="contact">Header form</form></header>' === $chrome_projection['chrome']['header'], 'overlapping chrome selectors fail atomically before provider side effects' );
$woo = Static_Site_Importer_Woo_Product_Seeder::binding_classic_render( array(), array( 'id' => 42 ) );
$form = Static_Site_Importer_Form_Seeder::binding_classic_render( array(), array( 'runtime_mapped' => true, 'block_markup' => '<!-- wp:jetpack/contact-form /-->' ) );
$assert( array( 'kind' => 'shortcode', 'content' => '[add_to_cart id="42"]' ) === $woo && 'blocks' === ( $form['kind'] ?? '' ) && str_contains( $form['content'] ?? '', 'jetpack/contact-form' ), 'Woo and Jetpack adapters expose actual provider-owned classic server render contracts' );
print "managed classic theme materialization smoke passed\n";
