<?php
/** Run: php tests/smoke-lifecycle-compile-checkpoint.php */
namespace {
	define( 'ABSPATH', dirname( __DIR__ ) . '/' );
	class WP_Error { public function __construct( private string $code, private string $message = '' ) {} public function get_error_code(): string { return $this->code; } public function get_error_message(): string { return $this->message; } }
	function is_wp_error( $value ): bool { return $value instanceof WP_Error; }
	function wp_json_encode( $value, int $options = 0 ) { return json_encode( $value, $options ); }
	function wp_mkdir_p( string $path ): bool { return is_dir( $path ) || mkdir( $path, 0700, true ); }
	function trailingslashit( string $path ): string { return rtrim( $path, '/\\' ) . '/'; }
	function get_theme_root(): string { return sys_get_temp_dir(); }
	function get_current_blog_id(): int { return 17; }
	function get_current_user_id(): int { return 23; }
	class Static_Site_Importer_Theme_Materialization_Strategy { const CLASSIC = 'classic'; public static function normalize( array $args ) { return array( 'strategy' => 'block', 'evidence' => array() ); } }
	class Static_Site_Importer_Content_Policy { public static function validate_artifact( array $artifact ) { return true; } }
	class Static_Site_Importer_Client_Script_Policy { public static function apply( array $artifact, array $args ): array { $artifact['script_policy_applied'] = true; return array( 'artifact' => $artifact, 'report' => array( 'policy' => 'inert' ) ); } }
	class Static_Site_Importer_Site_Identity { public static function resolve( array $args ): array { return array( 'name' => 'Checkpoint', 'slug' => 'checkpoint' ); } public static function title_from_website_artifact( array $artifact ): string { return ''; } }
	class Static_Site_Importer_Companion_Plugin { public static function validate_payload( array $payload ) { return true; } }
	class Static_Site_Importer_Entity_Materializer_Registry { public static function dependency_plan( array $lifecycle, string $hash ): array { return array(); } }
	class Static_Site_Importer_WordPress_Site_Plan_Materializer { public static function prepare( array $plan, array $args ): array { return array( 'status' => 'failed', 'receipt' => array( 'errors' => array( array( 'code' => 'test_stop', 'message' => 'stop after checkpoint restore' ) ) ) ); } }
	eval( 'namespace Automattic\\BlocksEngine\\PhpTransformer\\ArtifactCompiler { class ArtifactCompiler { public static int $calls = 0; public static array $artifacts = array(); public function compile( array $artifact ): object { ++self::$calls; self::$artifacts[] = $artifact; return new class { public function toArray(): array { return array( "source_reports" => array( "wordpress_site_plan" => array( "schema" => "test-plan/v1" ), "gutenberg_gaps" => array(), "materialization_plan" => array() ) ); } }; } } }' );
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-artifact-run.php';
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-lifecycle-compile-checkpoint.php';
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-theme-generator.php';
	$root = sys_get_temp_dir() . '/ssi-lifecycle-checkpoint-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $root );
	$artifact = array( 'schema' => 'test/v1', 'files' => array() );
	$args = array( 'slug' => 'checkpoint', 'name' => 'Checkpoint', '_static_site_importer_lifecycle_checkpoint_root' => $root );
	$prepared = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'prepare', 'runtime_lifecycle_invocation_id' => 'prepare-request' ) );
	if ( is_wp_error( $prepared ) || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls || ! preg_match( '/^[a-f0-9]{32}$/', $prepared['runtime_lifecycle_checkpoint'] ?? '' ) || empty( $prepared['fresh_runtime']['lifecycle_checkpoint_id'] ) || empty( \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$artifacts[0]['script_policy_applied'] ) ) { throw new \RuntimeException( 'prepare must compile once, return its handle, and retain a non-identity policy artifact' ); }
	$handle = $prepared['runtime_lifecycle_checkpoint'];
	$prepared_workspace = glob( $root . '/.ssi-artifact-run-lifecycle-' . $handle . '/workspace.json' )[0] ?? ''; $prepared_retention = json_decode( (string) file_get_contents( $prepared_workspace ), true ); if ( strtotime( (string) ( $prepared_retention['retention']['expires_at'] ?? '' ) ) < time() + 21600 - 2 ) { throw new \RuntimeException( 'default checkpoint retention must support at least six hours of retries' ); }
	$resumed = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'resume-request', 'runtime_lifecycle_checkpoint' => $handle ) );
	if ( ! is_wp_error( $resumed ) || 'test_stop' !== $resumed->get_error_code() || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'fresh resume must restore the checkpoint without compiling' ); }
	$same = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'prepare-request', 'runtime_lifecycle_checkpoint' => $handle ) );
	if ( ! is_wp_error( $same ) || 'static_site_importer_fresh_runtime_required' !== $same->get_error_code() || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'same invocation must be rejected before checkpoint use' ); }
	$legacy = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'legacy-request' ) );
	if ( ! is_wp_error( $legacy ) || 2 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'legacy resume without a handle must recompile' ); }
	$mismatch = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $handle, $artifact, array_merge( $args, array( 'slug' => 'other' ) ), 'test-owner', $root );
	if ( ! is_wp_error( $mismatch ) || 'static_site_importer_lifecycle_checkpoint_mismatch' !== $mismatch->get_error_code() ) { throw new \RuntimeException( 'argument mismatch must be rejected' ); }
	$owner = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $handle, $artifact, $args, 'other-owner', $root ); if ( ! is_wp_error( $owner ) ) { throw new \RuntimeException( 'cross-owner checkpoint use must be rejected' ); }
	$path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $handle . '/checkpoint.json' )[0] ?? ''; $record = json_decode( (string) file_get_contents( $path ), true ); $record['payload']['plan']['tampered'] = true; file_put_contents( $path, json_encode( $record ) );
	$tampered = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $handle, $artifact, $args, 'test-owner', $root ); if ( ! is_wp_error( $tampered ) ) { throw new \RuntimeException( 'tampered checkpoint must be rejected' ); }
	$payload = array( 'artifact' => $artifact, 'args' => $args, 'plan' => array( 'schema' => 'test-plan/v1' ), 'gutenberg_gaps' => array(), 'companion_payload' => null, 'materialization_plan' => array(), 'theme_materialization' => array() ); $expired = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'test-owner', $root ); $expired_path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $expired . '/workspace.json' )[0] ?? ''; $workspace = json_decode( (string) file_get_contents( $expired_path ), true ); $workspace['retention']['expires_at'] = gmdate( 'c', time() - 1 ); file_put_contents( $expired_path, json_encode( $workspace ) ); $expired_result = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $expired, $artifact, $args, 'test-owner', $root ); if ( ! is_wp_error( $expired_result ) || 'static_site_importer_lifecycle_checkpoint_expired' !== $expired_result->get_error_code() ) { throw new \RuntimeException( 'expired checkpoint must be purged and rejected' ); }
	$clean = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'test-owner', $root ); $loaded = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $clean, $artifact, $args, 'test-owner', $root ); $loaded['workspace']->cleanup( 'success' ); if ( is_dir( $loaded['workspace']->directory() ) ) { throw new \RuntimeException( 'successful checkpoint consumption must clean up the workspace' ); }
	$invalid = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'test-owner', $root ); $invalid_path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $invalid . '/checkpoint.json' )[0] ?? ''; $invalid_record = json_decode( (string) file_get_contents( $invalid_path ), true ); unset( $invalid_record['payload']['plan']['schema'] ); $invalid_record['payload_sha256'] = hash( 'sha256', json_encode( $invalid_record['payload'] ) ); file_put_contents( $invalid_path, json_encode( $invalid_record ) ); if ( ! is_wp_error( Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $invalid, $artifact, $args, 'test-owner', $root ) ) ) { throw new \RuntimeException( 'a checksummed checkpoint with an invalid plan shape must be rejected' ); }
	echo "Lifecycle compile checkpoint smoke passed.\n";
}
