<?php
/** Run: php tests/smoke-lifecycle-compile-checkpoint.php */
namespace {
	define( 'ABSPATH', dirname( __DIR__ ) . '/' );
	class WP_Error { public function __construct( private string $code, private string $message = '' ) {} public function get_error_code(): string { return $this->code; } public function get_error_message(): string { return $this->message; } }
	function is_wp_error( $value ): bool { return $value instanceof WP_Error; }
	function wp_json_encode( $value, int $options = 0 ) { return json_encode( $value, $options ); }
	function wp_mkdir_p( string $path ): bool { return is_dir( $path ) || mkdir( $path, 0700, true ); }
	function trailingslashit( string $path ): string { return rtrim( $path, '/\\' ) . '/'; }
	function apply_filters( string $hook, $value ) { if ( 'static_site_importer_lifecycle_checkpoint_implementation_binding' !== $hook ) { return $value; } $mode = getenv( 'SSI_CHECKPOINT_BINDING_MUTATION' ); if ( 'policy' === $mode ) { $value['content_policy']['file_sha256'] = 'changed-policy'; } if ( 'compiler' === $mode ) { $value['compiler']['dependencies_sha256'] = 'changed-compiler'; } return $value; }
	function wp_next_scheduled( string $hook ) { return $GLOBALS['ssi_scheduled'] ?? false; }
	function wp_schedule_event( int $timestamp, string $recurrence, string $hook ): bool { $GLOBALS['ssi_scheduled'] = $timestamp; return true; }
	function wp_clear_scheduled_hook( string $hook ): int { $cleared = empty( $GLOBALS['ssi_scheduled'] ) ? 0 : 1; unset( $GLOBALS['ssi_scheduled'] ); return $cleared; }
	function get_theme_root(): string { return sys_get_temp_dir(); }
	function get_current_blog_id(): int { return 17; }
	function get_current_user_id(): int { return 23; }
	class Static_Site_Importer_Theme_Materialization_Strategy { const CLASSIC = 'classic'; public static function normalize( array $args ) { return array( 'strategy' => 'block', 'evidence' => array() ); } }
	class Static_Site_Importer_Content_Policy { public static function validate_artifact( array $artifact ) { return true; } }
	class Static_Site_Importer_Client_Script_Policy { public static function apply( array $artifact, array $args ): array { $artifact['script_policy_applied'] = true; return array( 'artifact' => $artifact, 'report' => array( 'policy' => 'inert' ) ); } }
	class Static_Site_Importer_Site_Identity { public static function resolve( array $args ): array { return array( 'name' => 'Checkpoint', 'slug' => 'checkpoint' ); } public static function title_from_website_artifact( array $artifact ): string { return ''; } }
	class Static_Site_Importer_Companion_Plugin { public static function validate_payload( array $payload ) { return true; } }
	class Static_Site_Importer_Entity_Materializer_Registry { public static function dependency_plan( array $lifecycle, string $hash ): array { return array(); } }
	class Static_Site_Importer_WordPress_Site_Plan_Materializer { public static function prepare( array $plan, array $args ): array { return array( 'status' => 'failed', 'receipt' => array( 'errors' => array( array( 'code' => 'test_stop', 'message' => 'stop after checkpoint restore' ) ) ) ); } public static function prepare_for_materialization( array $plan, array $args ): array { return 'prepare' === ( $args['runtime_lifecycle_phase'] ?? '' ) ? array( 'status' => 'prepared', 'args' => $args, 'resolved' => array() ) : self::prepare( $plan, $args ); } public static function materialize_runtime_dependencies( array $lifecycle, array $args ): array { return array(); } }
	eval( 'namespace Automattic\\BlocksEngine\\PhpTransformer\\ArtifactCompiler { class ArtifactCompiler { public static int $calls = 0; public static array $artifacts = array(); public function compile( array $artifact ): object { ++self::$calls; self::$artifacts[] = $artifact; return new class { public function toWordPressSitePlanView(): array { return array( "schema" => "blocks-engine/wordpress-site-plan-view/v1", "wordpress_site_plan" => array( "schema" => "test-plan/v1" ), "gutenberg_gaps" => array(), "companion_plugin_payload" => array(), "font_materialization" => array(), "diagnostics" => array() ); } public function toArray(): array { throw new \\RuntimeException( "complete compiler envelope must not be projected" ); } }; } } }' );
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-artifact-run.php';
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-lifecycle-compile-checkpoint.php';
	require_once dirname( __DIR__ ) . '/includes/class-static-site-importer-theme-generator.php';
	if ( '--checkpoint-child' === ( $argv[1] ?? '' ) ) {
		$artifact = array( 'schema' => 'test/v1', 'files' => array() ); $args = array( 'slug' => (string) ( $argv[6] ?? 'checkpoint' ), 'name' => 'Checkpoint', 'source_metadata' => array( 'source' => 'fixture' ) ); $loaded = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( (string) $argv[2], $artifact, $args, (string) ( $argv[4] ?? 'site:17;user:23' ), (string) $argv[3] );
		if ( is_wp_error( $loaded ) ) { fwrite( STDERR, $loaded->get_error_code() ); exit( 1 ); }
		if ( in_array( $argv[5] ?? '', array( 'claim', 'consume' ), true ) ) { $claim = Static_Site_Importer_Lifecycle_Compile_Checkpoint::claim( $loaded['workspace'] ); if ( is_wp_error( $claim ) ) { fwrite( STDERR, $claim->get_error_code() ); exit( 1 ); } if ( 'consume' === ( $argv[5] ?? '' ) ) { $loaded['workspace']->cleanup( 'success' ); } }
		exit( 0);
	}
	$root = sys_get_temp_dir() . '/ssi-lifecycle-checkpoint-' . bin2hex( random_bytes( 4 ) ); wp_mkdir_p( $root );
	$artifact = array( 'schema' => 'test/v1', 'files' => array() );
	$args = array( 'slug' => 'checkpoint', 'name' => 'Checkpoint', 'source_metadata' => array( 'source' => 'fixture' ), '_static_site_importer_lifecycle_checkpoint_root' => $root );
	$prepared = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'prepare', 'runtime_lifecycle_invocation_id' => 'prepare-request' ) );
	if ( is_wp_error( $prepared ) || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls || ! preg_match( '/^[a-f0-9]{32}$/', $prepared['runtime_lifecycle_checkpoint'] ?? '' ) || empty( $prepared['fresh_runtime']['lifecycle_checkpoint_id'] ) || empty( \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$artifacts[0]['script_policy_applied'] ) ) { throw new \RuntimeException( 'prepare must compile once, return its handle, and retain a non-identity policy artifact' ); }
	$handle = $prepared['runtime_lifecycle_checkpoint'];
	if ( empty( $GLOBALS['ssi_scheduled'] ) ) { throw new \RuntimeException( 'checkpoint creation must schedule bounded cleanup when WP-Cron is available' ); }
	Static_Site_Importer_Lifecycle_Compile_Checkpoint::unschedule_cleanup();
	if ( ! empty( $GLOBALS['ssi_scheduled'] ) ) { throw new \RuntimeException( 'checkpoint cleanup must be unscheduled on plugin deactivation' ); }
	Static_Site_Importer_Lifecycle_Compile_Checkpoint::register_cleanup();
	if ( empty( $GLOBALS['ssi_scheduled'] ) ) { throw new \RuntimeException( 'checkpoint cleanup must be schedulable after plugin reactivation' ); }
	$prepared_workspace = glob( $root . '/.ssi-artifact-run-lifecycle-' . $handle . '/workspace.json' )[0] ?? ''; $prepared_retention = json_decode( (string) file_get_contents( $prepared_workspace ), true ); if ( strtotime( (string) ( $prepared_retention['retention']['expires_at'] ?? '' ) ) < time() + 21600 - 2 ) { throw new \RuntimeException( 'default checkpoint retention must support at least six hours of retries' ); }
	$resumed = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'resume-request', 'runtime_lifecycle_checkpoint' => $handle ) );
	if ( ! is_wp_error( $resumed ) || 'static_site_importer_fresh_runtime_required' !== $resumed->get_error_code() || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'a different caller invocation must not bypass the same-runtime guard' ); }
	$child = static function ( string $mode = '', string $owner = 'site:17;user:23', string $action = '', string $checkpoint = '', string $slug = 'checkpoint' ) use ( $handle, $root ): array { $checkpoint = '' !== $checkpoint ? $checkpoint : $handle; $command = (string) PHP_BINARY . ' ' . escapeshellarg( __FILE__ ) . ' --checkpoint-child ' . escapeshellarg( $checkpoint ) . ' ' . escapeshellarg( $root ) . ' ' . escapeshellarg( $owner ) . ' ' . escapeshellarg( $action ) . ' ' . escapeshellarg( $slug ); $environment = '' === $mode ? null : array_merge( $_ENV, array( 'SSI_CHECKPOINT_BINDING_MUTATION' => $mode ) ); $process = proc_open( $command, array( 1 => array( 'pipe', 'w' ), 2 => array( 'pipe', 'w' ) ), $pipes, null, $environment ); $output = is_resource( $process ) ? stream_get_contents( $pipes[1] ) . stream_get_contents( $pipes[2] ) : ''; if ( is_resource( $process ) ) { fclose( $pipes[1] ); fclose( $pipes[2] ); $status = proc_close( $process ); } else { $status = 1; } return array( $status, $output ); };
	$fresh = $child(); if ( 0 !== $fresh[0] ) { throw new \RuntimeException( 'a separate PHP process must load a valid checkpoint: ' . $fresh[1] ); }
	$direct_args = $args;
	$direct_args['client_script_policy_report'] = array( 'policy' => 'isolated_preview' );
	$direct_args['compiled_artifact_result'] = array( 'schema' => 'blocks-engine/php-transformer/result/v1' );
	$direct_args['_static_site_importer_precompiled_source'] = true;
	$direct_args['import_run_id'] = str_repeat( 'a', 64 );
	$direct_args['source_metadata']['collection']['script_policy'] = array( 'policy' => 'isolated_preview' );
	$direct_payload = array( 'artifact' => $artifact, 'args' => $direct_args, 'plan' => array( 'schema' => 'test-plan/v1' ), 'gutenberg_gaps' => array(), 'companion_payload' => null, 'materialization_plan' => array(), 'theme_materialization' => array() );
	$direct = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $direct_args, $direct_payload, 'site:17;user:23', $root );
	$direct_fresh = $child( '', 'site:17;user:23', '', $direct );
	if ( 0 !== $direct_fresh[0] ) { throw new \RuntimeException( 'a direct artifact checkpoint must bind caller inputs rather than derived compile fields: ' . $direct_fresh[1] ); }
	Static_Site_Importer_Lifecycle_Compile_Checkpoint::discard( $direct, $root );
	$policy_changed = $child( 'policy' ); if ( 0 === $policy_changed[0] || ! str_contains( $policy_changed[1], 'static_site_importer_lifecycle_checkpoint_mismatch' ) ) { throw new \RuntimeException( 'policy fingerprint changes must reject the checkpoint' ); }
	$compiler_changed = $child( 'compiler' ); if ( 0 === $compiler_changed[0] || ! str_contains( $compiler_changed[1], 'static_site_importer_lifecycle_checkpoint_mismatch' ) ) { throw new \RuntimeException( 'compiler dependency fingerprint changes must reject the checkpoint' ); }
	$same = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'prepare-request', 'runtime_lifecycle_checkpoint' => $handle ) );
	if ( ! is_wp_error( $same ) || 'static_site_importer_fresh_runtime_required' !== $same->get_error_code() || 1 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'same invocation must be rejected before checkpoint use' ); }
	$legacy = Static_Site_Importer_Theme_Generator::import_website_artifact( $artifact, $args + array( 'runtime_lifecycle_phase' => 'resume', 'runtime_lifecycle_request_id' => 'prepare-request', 'runtime_lifecycle_invocation_id' => 'legacy-request' ) );
	if ( ! is_wp_error( $legacy ) || 2 !== \Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler::$calls ) { throw new \RuntimeException( 'legacy resume without a handle must recompile' ); }
	$mismatch = $child( '', 'site:17;user:23', '', '', 'other' );
	if ( 0 === $mismatch[0] || ! str_contains( $mismatch[1], 'static_site_importer_lifecycle_checkpoint_mismatch' ) ) { throw new \RuntimeException( 'argument mismatch must be rejected' ); }
	$owner = $child( '', 'other-owner' ); if ( 0 === $owner[0] || ! str_contains( $owner[1], 'static_site_importer_lifecycle_checkpoint_mismatch' ) ) { throw new \RuntimeException( 'cross-owner checkpoint use must be rejected' ); }
	$path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $handle . '/checkpoint.json' )[0] ?? ''; $record = json_decode( (string) file_get_contents( $path ), true ); $record['payload']['plan']['tampered'] = true; file_put_contents( $path, json_encode( $record ) );
	$tampered = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $handle, $artifact, $args, 'test-owner', $root ); if ( ! is_wp_error( $tampered ) ) { throw new \RuntimeException( 'tampered checkpoint must be rejected' ); }
	$payload = array( 'artifact' => $artifact, 'args' => $args, 'plan' => array( 'schema' => 'test-plan/v1' ), 'gutenberg_gaps' => array(), 'companion_payload' => null, 'materialization_plan' => array(), 'theme_materialization' => array() ); $expired = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'test-owner', $root ); $expired_path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $expired . '/workspace.json' )[0] ?? ''; $workspace = json_decode( (string) file_get_contents( $expired_path ), true ); $workspace['retention']['expires_at'] = gmdate( 'c', time() - 1 ); file_put_contents( $expired_path, json_encode( $workspace ) ); $expired_result = Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $expired, $artifact, $args, 'test-owner', $root ); if ( ! is_wp_error( $expired_result ) || 'static_site_importer_lifecycle_checkpoint_expired' !== $expired_result->get_error_code() ) { throw new \RuntimeException( 'expired checkpoint must be purged and rejected' ); }
	$clean = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'site:17;user:23', $root ); $consumed = $child( '', 'site:17;user:23', 'consume', $clean ); if ( 0 !== $consumed[0] || is_dir( $root . '/.ssi-artifact-run-lifecycle-' . $clean ) ) { throw new \RuntimeException( 'successful checkpoint consumption must clean up the workspace' ); }
	$claim = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'site:17;user:23', $root ); $claimer = $child( '', 'site:17;user:23', 'claim', $claim ); $replay = $child( '', 'site:17;user:23', 'claim', $claim ); Static_Site_Importer_Lifecycle_Compile_Checkpoint::discard( $claim, $root ); if ( 0 !== $claimer[0] || 0 === $replay[0] || ! str_contains( $replay[1], 'static_site_importer_lifecycle_checkpoint_claimed' ) ) { throw new \RuntimeException( 'only one concurrent checkpoint consumer may claim materialization' ); }
	$invalid = Static_Site_Importer_Lifecycle_Compile_Checkpoint::create( $artifact, $args, $payload, 'test-owner', $root ); $invalid_path = glob( $root . '/.ssi-artifact-run-lifecycle-' . $invalid . '/checkpoint.json' )[0] ?? ''; $invalid_record = json_decode( (string) file_get_contents( $invalid_path ), true ); unset( $invalid_record['payload']['plan']['schema'] ); $invalid_record['payload_sha256'] = hash( 'sha256', json_encode( $invalid_record['payload'] ) ); file_put_contents( $invalid_path, json_encode( $invalid_record ) ); if ( ! is_wp_error( Static_Site_Importer_Lifecycle_Compile_Checkpoint::load( $invalid, $artifact, $args, 'test-owner', $root ) ) ) { throw new \RuntimeException( 'a checksummed checkpoint with an invalid plan shape must be rejected' ); }
	echo "Lifecycle compile checkpoint smoke passed.\n";
}
